USE MASTER
GO
CREATE DATABASE EDUSYS
USE EDUSYS 
GO

CREATE TABLE NHANVIEN(
	MANV NVARCHAR(50) PRIMARY KEY,
	MATKHAU NVARCHAR(50) NOT NULL,
	HO NVARCHAR(30) NOT NULL,
	TEN NVARCHAR(20) NOT NULL,
	VAITRO BIT DEFAULT 0
);

GO

CREATE TABLE CHUYENDE(
	MACD NVARCHAR(5) PRIMARY KEY NOT NULL,
	TENCD NVARCHAR(50) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	HINH NVARCHAR(50) NOT NULL,
	MOTA NVARCHAR(250) NOT NULL
);

GO 

CREATE TABLE KHOAHOC(
	MAKH  INT IDENTITY(1,1) PRIMARY KEY,
	MACD NVARCHAR(5) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	NGAYKG DATE NOT NULL,
	GHICHU NVARCHAR(250) NULL,
	MANV NVARCHAR(50) NOT NULL,
	NGAYTAO DATE DEFAULT GETDATE(),
	FOREIGN KEY (MACD) REFERENCES CHUYENDE(MACD) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE
);
SET IDENTITY_INSERT KHOAHOC ON
GO 

CREATE TABLE NGUOIHOC(
	MANH NVARCHAR(7) PRIMARY KEY,
	HO NVARCHAR(30) NOT NULL,
	TEN NVARCHAR(20) NOT NULL,
	GIOITINH BIT DEFAULT 1,
	NGAYSINH DATE NOT NULL,
	DIENTHOAI NVARCHAR(10) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(250) NULL,
	MANV NVARCHAR(50) NOT NULL,
	NGAYDK DATE DEFAULT GETDATE(),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE
);

GO 

CREATE TABLE HOCVIEN(
	MAHV INT IDENTITY(1,1) PRIMARY KEY,
	MAKH INT NOT NULL,
	MANH NVARCHAR(7) NOT NULL,
	DIEM FLOAT NOT NULL,
	FOREIGN KEY (MANH) REFERENCES NGUOIHOC(MANH) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (MAKH) REFERENCES KHOAHOC(MAKH) ON DELETE NO ACTION ON UPDATE NO ACTION
);
SET IDENTITY_INSERT HOCVIEN ON
USE EDUSYS
GO 
--REPORT MANH - HOTEN - DIEM
CREATE PROCEDURE SP_BANGDIEM(@MAKH INT)
	AS 
		BEGIN
			SELECT NH.MANH, NH.HO+NH.TEN AS HOTEN, HV.DIEM 
			FROM HOCVIEN HV 
				JOIN NGUOIHOC NH ON NH.MANH = HV.MANH
			WHERE HV.MAKH = @MAKH
			ORDER BY HV.DIEM DESC
		END
	GO

--REPORT TENCD - SOHV - THAPNHAT - CAONHAT - TRUNGBINH
CREATE PROCEDURE SP_THONGKEDIEM
	AS 
		BEGIN
			SELECT CD.TENCD AS CHUYENDE, 
				COUNT(HV.MAHV) AS SOHV,
				MIN(HV.DIEM) AS THAPNHAT,
				MAX(HV.DIEM) AS CAONHAT,
				AVG(HV.DIEM) AS TRUNGBINH
			FROM KHOAHOC KH 
				JOIN HOCVIEN HV ON KH.MAKH = HV.MAKH
				JOIN CHUYENDE CD ON CD.MACD = KH.MACD
			GROUP BY CD.TENCD
		END
	GO

--REPORT TENCD - SOKH - SOHV - DOANHTHU - THAPNHAT - CAONHAT - TRUNGBINH
CREATE PROCEDURE SP_THONGKEDOANHTHU(@YEAR INT)
	AS
		BEGIN
			SELECT 
				CD.TENCD AS CHUYENDE,
				COUNT(DISTINCT KH.MAKH) AS SOKH,
				COUNT(HV.MAHV) AS SOHV,
				SUM(KH.HOCPHI) AS DOANHTHU,
				MIN(KH.HOCPHI) AS THAPNHAT,
				MAX(KH.HOCPHI) AS CAONHAT,
				AVG(KH.HOCPHI) AS TRUNGBINH
			FROM KHOAHOC KH
				JOIN HOCVIEN HV ON KH.MAKH = HV.MAKH
				JOIN CHUYENDE CD ON CD.MACD = KH.MACD
			WHERE YEAR(NGAYKG) = @YEAR
			GROUP BY CD.TENCD
		END
	GO

--REPORT NAW - SOLUONG - DAUTIEN - CUOICUNG
CREATE PROCEDURE SP_THONGKENGUOIHOC
	AS
		BEGIN
			SELECT 
				YEAR(NGAYDK) AS NAM,
				COUNT(*) AS SOLUONG,
				MIN(NGAYDK) AS DAUTIEN,
				MAX(NGAYDK) AS CUOICUNG
			FROM NGUOIHOC
			GROUP BY YEAR(NGAYDK)
		END
	GO
	
	--Insert data
	--Insert nhanvien 
		INSERT INTO NHANVIEN(MANV, MATKHAU, HO, TEN, VAITRO) VALUES('admin', 'admin123', N'Lê Văn', N'Tèo', 1)
	INSERT INTO NHANVIEN(MANV, MATKHAU, HO, TEN, VAITRO) VALUES('nhanvien', 'nhanvien123', N'Trần Văn', N'Minh', 0)
		--Insert chuyende
	INSERT INTO CHUYENDE (MACD,TENCD, HOCPHI, THOILUONG, HINH, MOTA) 
	VALUES('CD001', 'JAVA', 2000000, 20, 'A.PNG', 'CHUYENDE JAVA'),
	('CD002', 'JAVA', 3000000, 15, 'A.PNG', 'CHUYENDE JAVA'), 
	('CD003',N'Thiet ke Wed',4000000,15,'A.PNG','CHUYENDE WED'),
	('CD004','C#',3000000,20,'A.PNG', 'CHUYENDE C#')	
	--Insert khoahoc
	SET IDENTITY_INSERT KHOAHOC OFF
	INSERT INTO KHOAHOC (MACD, HOCPHI, THOILUONG, NGAYKG, NGAYTAO, MANV, GHICHU) 
	VALUES ('CD001', 2000000, 20, '2021-10-15', '2021-10-12', 'admin', 'aa'),
	('CD001', 2000000, 20, '2021-10-25',' 2021-10-12', 'admin', 'aa'),
	('CD003',4000000,15,'2021-09-14','2021-09-01','admin','are you ok ?'),
	('CD003',4000000,15,'2021-09-30','2021-09-21','admin','ok ok ok ?')
	--Insert nguoihoc
	INSERT INTO NGUOIHOC (MANH, HO, TEN, GIOITINH,NGAYSINH,EMAIL,MANV,NGAYDK, DIENTHOAI, GHICHU ) 
	VALUES ('NH011','Nguyen','A',1,'2002-01-07','A@gmail.com','admin','2020-09-12','0769331203', 'ok' ),
	('NH012','Nguyen','B',1,'2002-01-07','B@gmail.com','admin','2020-09-14','0779331203', 'ok' )
	--Insert into hocvien
	insert into HOCVIEN(MANH,MAKH,DIEM) 
	values('NH011',2,8),
	('NH011',3,10)

/*
	--THEM DU LIEU
	INSERT INTO NHANVIEN(MANV, MATKHAU, HO, TEN, VAITRO) VALUES('admin', 'admin123', N'Lê Văn', N'Tèo', 1)
	INSERT INTO NHANVIEN(MANV, MATKHAU, HO, TEN, VAITRO) VALUES('nhanvien', 'nhanvien123', N'Trần Văn', N'Minh', 0)

	INSERT INTO CHUYENDE (MACD,TENCD, HOCPHI, THOILUONG, HINH, MOTA) VALUES('CD001', 'JAVA', 2000000, 20, 'A.PNG', 'CHUYENDE JAVA'),
	('CD002', 'JAVA', 3000000, 15, 'A.PNG', 'CHUYENDE JAVA')
	

	INSERT INTO KHOAHOC (MACD, HOCPHI, THOILUONG, NGAYKG, NGAYTAO, MANV, GHICHU) 
	VALUES ('CD001', 2000000, 20, 2021-10-15, 2021-10-12, 'admin', 'aa'),
	('CD001', 2000000, 20, 2021-10-25, 2021-10-12, 'admin', 'aa')

		
		INSERT INTO NGUOIHOC (MANH, HO, TEN, GIOITINH,NGAYSINH,EMAIL,MANV,NGAYDK, DIENTHOAI, GHICHU ) 
	VALUES ('NH011','Nguyen','A',1,'2002-01-07','A@gmail.com','admin','2020-09-12','0769331203', 'ok' )
	insert into HOCVIEN(MANH,MAKH,DIEM) values('NH011',0,8)*/



/*	use master 
	drop database EDUSYS*/
--CAC CAU LENH SQL
/*
INSERT INTO NHANVIEN(MANV, MATKHAU, HO, TEN, VAITRO)
VALUES (?, ?, ?, ?, ?)
UPDATE NHANVIEN SET MATKHAU =?, HO =?, TEN =?, VAITRO = ? WHERE MANV =?, 
DELETE FROM NHANVIEN WHERE MANV = ?
SELECT * FROM NHANVIEN WHERE MANV =? 

INSERT INTO CHUYENDE(MACD, TENCD, HOCPHI, THOILUONG, HINH, MOTA) VALUES (?, ?, ?, ?, ?, ?)
UPDATE CHUYENDE SET TENCD = ?, HOCPHI = ?, THOILUONG = ?, HINH=?  WHERE MACD = ?
DELETE FROM CHUYENDE WHERE MACD = ?
SELECT * FROM CHUYENDE WHERE MACD = ?

INSERT INTO NGUOIHOC (MANH, HO, TEN, GIOITINH, NGAYSINH, DIENTHOAI, EMAIL, GHICHU, MANV, NGAYDK)
VALUES (?,?,?,?,?,?,?,?,?,?)
UPDATE NGUOIHOC SET HO =?, TEN =?, GIOITINH =?, NGAYSINH =?, DIENTHOAI =?, EMAIL =?, GHICHU =?, MANV =?, NGAYDK =? WHERE MANH = ?
DELETE FROM NGUOIHOC WHERE MANH = ?
SELECT * FROM NGUOIHOC

INSERT INTO KHOAHOC (MAKH, MACD, HOCPHI, THOILUONG, NGAYKG, GHICHU, MANV, NGAYTAO)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
UPDATE KHOAHOC
SET          MACD = ?, HOCPHI = ?, THOILUONG = ?, NGAYKG = ?, GHICHU = ?, MANV = ?, NGAYTAO = ? WHERE MAKH = ?
DELETE FROM KHOAHOC WHERE MAKH = ?
SELECT * FROM KHOAHOC WHERE MAKH = ?

INSERT INTO HOCVIEN (MAHV, MAKH, MANH, DIEM) VALUES (?, ?, ?, ?)
UPDATE HOCVIEN SET MAKH =?, MANH = ?, DIEM = ? WHERE MAHV =?
DELETE FROM HOCVIEN WHERE MAHV = ?
SELECT * FROM HOCVIEN WHERE MAHV = ?
*/
/*SELECT * FROM CHUYENDE WHERE MACD = 'CD001' AND MACD IN (SELECT MACD FROM KHOAHOC)

SELECT HV.MAHV, HV.MANH, HV.MAKH,NH.HO+ ' '+ NH.TEN, HV.DIEM FROM HOCVIEN HV JOIN NGUOIHOC NH ON HV.MANH=NH.MANH  WHERE HV.MAKH = ?
UPDATE KHOAHOC SET NGAYKG = '2021-11-05' WHERE MAKH = 3

CREATE TRIGGER TRG_XOAKHOAHOC
ON KHOAHOC
INSTEAD OF DELETE
AS
BEGIN
	DELETE FROM HOCVIEN WHERE MAKH IN (SELECT MAKH FROM DELETED)
	DELETE FROM KHOAHOC WHERE MAKH IN (SELECT MAKH FROM DELETED)
END 

DROP TRIGGER TRG_XOAKHOAHOC 

CREATE TRIGGER TRG_XOACHUYENDE
ON CHUYENDE
INSTEAD OF DELETE
AS
BEGIN
	DELETE FROM KHOAHOC WHERE MACD IN (SELECT MACD FROM INSERTED)
	DELETE FROM CHUYENDE WHERE MACD IN (SELECT MACD FROM INSERTED)
END
DROP TRIGGER TRG_XOACHUYENDE*/