USE MASTER
GO
CREATE DATABASE EDUSYS
USE EDUSYS 
GO

CREATE TABLE NHANVIEN(
	MANV NVARCHAR(50) PRIMARY KEY,
	MATKHAU NVARCHAR(50) NOT NULL,
	HO NVARCHAR(30) NOT NULL,
	TEN NVARCHAR(20) NOT NULL,
	VAITRO BIT DEFAULT 0
);

GO

CREATE TABLE CHUYENDE(
	MACD NVARCHAR(5) PRIMARY KEY NOT NULL,
	TENCD NVARCHAR(50) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	HINH NVARCHAR(50) NOT NULL,
	MOTA NVARCHAR(MAX) NOT NULL
);

GO 

CREATE TABLE KHOAHOC(
	MAKH  INT IDENTITY(1,1) PRIMARY KEY,
	MACD NVARCHAR(5) NOT NULL,
	HOCPHI FLOAT NOT NULL,
	THOILUONG INT NOT NULL,
	NGAYKG DATE NOT NULL,
	GHICHU NVARCHAR(MAX) NULL,
	MANV NVARCHAR(50) NOT NULL,
	NGAYTAO DATE DEFAULT GETDATE(),
	FOREIGN KEY (MACD) REFERENCES CHUYENDE(MACD) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE
);

GO 

CREATE TABLE NGUOIHOC(
	MANH NVARCHAR(7) PRIMARY KEY,
	HO NVARCHAR(30) NOT NULL,
	TEN NVARCHAR(20) NOT NULL,
	GIOITINH BIT DEFAULT 1,
	NGAYSINH DATE NOT NULL,
	DIENTHOAI NVARCHAR(10) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	GHICHU NVARCHAR(MAX) NULL,
	MANV NVARCHAR(50) NOT NULL,
	NGAYDK DATE DEFAULT GETDATE(),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE
);

GO 

CREATE TABLE HOCVIEN(
	MAHV INT IDENTITY(1,1) PRIMARY KEY,
	MAKH INT NOT NULL,
	MANH NVARCHAR(7) NOT NULL,
	DIEM FLOAT NOT NULL,
	FOREIGN KEY (MANH) REFERENCES NGUOIHOC(MANH) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (MAKH) REFERENCES KHOAHOC(MAKH) ON DELETE NO ACTION ON UPDATE NO ACTION
);

USE MASTER 
DROP DATABASE EDUSYS

USE EDUSYS
GO 
--REPORT MANH - HOTEN - DIEM
CREATE PROCEDURE SP_BANGDIEM(@MAKH INT)
	AS 
		BEGIN
			SELECT NH.MANH, NH.HO+NH.TEN AS HOTEN, HV.DIEM 
			FROM HOCVIEN HV 
				JOIN NGUOIHOC NH ON NH.MANH = HV.MANH
			WHERE HV.MAKH = @MAKH
			ORDER BY HV.DIEM DESC
		END
	GO

--REPORT TENCD - SOHV - THAPNHAT - CAONHAT - TRUNGBINH
CREATE PROCEDURE SP_THONGKEDIEM
	AS 
		BEGIN
			SELECT CD.TENCD AS CHUYENDE, 
				COUNT(HV.MAHV) AS SOHV,
				MIN(HV.DIEM) AS THAPNHAT,
				MAX(HV.DIEM) AS CAONHAT,
				AVG(HV.DIEM) AS TRUNGBINH
			FROM KHOAHOC KH 
				JOIN HOCVIEN HV ON KH.MAKH = HV.MAKH
				JOIN CHUYENDE CD ON CD.MACD = KH.MACD
			GROUP BY CD.TENCD
		END
	GO

--REPORT TENCD - SOKH - SOHV - DOANHTHU - THAPNHAT - CAONHAT - TRUNGBINH
CREATE PROCEDURE SP_THONGKEDOANHTHU(@YEAR INT)
	AS
		BEGIN
			SELECT 
				CD.TENCD AS CHUYENDE,
				COUNT(DISTINCT KH.MAKH) AS SOKH,
				COUNT(HV.MAHV) AS SOHV,
				SUM(KH.HOCPHI) AS DOANHTHU,
				MIN(KH.HOCPHI) AS THAPNHAT,
				MAX(KH.HOCPHI) AS CAONHAT,
				AVG(KH.HOCPHI) AS TRUNGBINH
			FROM KHOAHOC KH
				JOIN HOCVIEN HV ON KH.MAKH = HV.MAKH
				JOIN CHUYENDE CD ON CD.MACD = KH.MACD
			WHERE YEAR(NGAYKG) = @YEAR
		END
	GO

--REPORT NAW - SOLUONG - DAUTIEN - CUOICUNG
CREATE PROCEDURE SP_THONGKENGUOIHOC
	AS
		BEGIN
			SELECT 
				YEAR(NGAYDK) AS NAM,
				COUNT(*) AS SOLUONG,
				MIN(NGAYDK) AS DAUTIEN,
				MAX(NGAYDK) AS CUOICUNG
			FROM NGUOIHOC
			GROUP BY YEAR(NGAYDK)
		END
	GO

	
--CAC CAU LENH SQL

INSERT INTO NHANVIEN(MANV, MATKHAU, HO, TEN, VAITRO)
VALUES (?, ?, ?, ?, ?)
UPDATE NHANVIEN SET MATKHAU =?, HO =?, TEN =?, VAITRO = ? WHERE MANV =?, 
DELETE FROM NHANVIEN WHERE MANV = ?
SELECT * FROM NHANVIEN WHERE MANV =? 

INSERT INTO CHUYENDE(MACD, TENCD, HOCPHI, THOILUONG, HINH, MOTA) VALUES (?, ?, ?, ?, ?, ?)
UPDATE CHUYENDE SET TENCD = ?, HOCPHI = ?, THOILUONG = ?, HINH=?  WHERE MACD = ?
DELETE FROM CHUYENDE WHERE MACD = ?
SELECT * FROM CHUYENDE WHERE MACD = ?

INSERT INTO NGUOIHOC (MANH, HO, TEN, GIOITINH, NGAYSINH, DIENTHOAI, EMAIL, GHICHU, MANV, NGAYDK)
VALUES (?,?,?,?,?,?,?,?,?,?)
UPDATE NGUOIHOC SET HO =?, TEN =?, GIOITINH =?, NGAYSINH =?, DIENTHOAI =?, EMAIL =?, GHICHU =?, MANV =?, NGAYDK =? WHERE MANH = ?
DELETE FROM NGUOIHOC WHERE MANH = ?
SELECT * FROM NGUOIHOC

INSERT INTO KHOAHOC (MAKH, MACD, HOCPHI, THOILUONG, NGAYKG, GHICHU, MANV, NGAYTAO)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
UPDATE KHOAHOC
SET          MACD = ?, HOCPHI = ?, THOILUONG = ?, NGAYKG = ?, GHICHU = ?, MANV = ?, NGAYTAO = ? WHERE MAKH = ?
DELETE FROM KHOAHOC WHERE MAKH = ?
SELECT * FROM KHOAHOC WHERE MAKH = ?

INSERT INTO HOCVIEN (MAHV, MAKH, MANH, DIEM) VALUES (?, ?, ?, ?)
UPDATE HOCVIEN SET MAKH =?, MANH = ?, DIEM = ? WHERE MAHV =?
DELETE FROM HOCVIEN WHERE MAHV = ?
SELECT * FROM HOCVIEN WHERE MAHV = ?
