/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import AppPackage.AnimationClass;
import com.edusys.dao.ChuyenDeDAO;
import com.edusys.entity.ChuyenDe;
import com.edusys.helper.Auth;
import com.edusys.helper.MsgBox;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.*;
import javax.swing.JToggleButton;

/**
 *
 * @author haotn
 */
public final class EduSys_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form EduSys_JFrame
     */
//    private PanelContainer container = new PanelContainer();
    CardLayout layout;
    AnimationClass ac = new AnimationClass();
    boolean accountToolHide = true;
    String userName = Auth.user.getHo() + " " + Auth.user.getTen();
    String user = Auth.user.getMaNV();

    public EduSys_JFrame() {
        initComponents();
        setLocationRelativeTo(null);
        layout = (CardLayout) pnlRight.getLayout();
        addCard();
        selectedButton(btnTrangChu);
        lblUser.setText(user);
        lblUsername.setText("Xin chào " + Auth.user.getHo() + " " + Auth.user.getTen() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblAccountDoiMatKhau = new javax.swing.JLabel();
        lblAcountDangXuat = new javax.swing.JLabel();
        lblAccountThoat = new javax.swing.JLabel();
        lblBackgroundAccountTool = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        lblHeThong = new javax.swing.JLabel();
        btnGioiThieu = new javax.swing.JToggleButton();
        btnTrangChu = new javax.swing.JToggleButton();
        btnHuongDan = new javax.swing.JToggleButton();
        btnQuanLyNhanVien = new javax.swing.JToggleButton();
        btnQuanLyHocVien = new javax.swing.JToggleButton();
        btnQuanLyNguoiHoc = new javax.swing.JToggleButton();
        btnQuanLyKhoaHoc = new javax.swing.JToggleButton();
        btnDoanhThu = new javax.swing.JToggleButton();
        btnBangDiem = new javax.swing.JToggleButton();
        btnLuongNguoiHoc = new javax.swing.JToggleButton();
        btnDiemTheoChuyenDe = new javax.swing.JToggleButton();
        btnQuanLyChuyenDe = new javax.swing.JToggleButton();
        lblQuanLy = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        lblBackgroundLeft = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainer.setMaximumSize(new java.awt.Dimension(1400, 800));
        pnlContainer.setMinimumSize(new java.awt.Dimension(1400, 800));
        pnlContainer.setPreferredSize(new java.awt.Dimension(1400, 800));
        pnlContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setMaximumSize(new java.awt.Dimension(1400, 50));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/user.png"))); // NOI18N
        lblUser.setText("Use: Admin");
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });
        header.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 140, 50));

        jLabel41.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("EduSys");
        header.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        lblUsername.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Version 1.0");
        header.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/header_1.jpg"))); // NOI18N
        header.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 50));

        pnlContainer.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblAccountDoiMatKhau.setBackground(new java.awt.Color(35, 75, 72));
        lblAccountDoiMatKhau.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAccountDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/DoiMatKhau.png"))); // NOI18N
        lblAccountDoiMatKhau.setText("Đổi mật khẩu");
        lblAccountDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccountDoiMatKhauMouseClicked(evt);
            }
        });
        pnlContainer.add(lblAccountDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, -60, 200, 30));

        lblAcountDangXuat.setBackground(new java.awt.Color(35, 75, 72));
        lblAcountDangXuat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAcountDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblAcountDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/DangXuat.png"))); // NOI18N
        lblAcountDangXuat.setText("Đăng xuất");
        lblAcountDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcountDangXuatMouseClicked(evt);
            }
        });
        pnlContainer.add(lblAcountDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, -30, 200, 30));

        lblAccountThoat.setBackground(new java.awt.Color(35, 75, 72));
        lblAccountThoat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAccountThoat.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Thoat.png"))); // NOI18N
        lblAccountThoat.setText("Thoát");
        lblAccountThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccountThoatMouseClicked(evt);
            }
        });
        pnlContainer.add(lblAccountThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 200, 30));

        lblBackgroundAccountTool.setBackground(new java.awt.Color(35, 75, 72));
        lblBackgroundAccountTool.setOpaque(true);
        pnlContainer.add(lblBackgroundAccountTool, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, -60, 200, 90));

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setMaximumSize(new java.awt.Dimension(200, 750));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeThong.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblHeThong.setForeground(new java.awt.Color(255, 204, 0));
        lblHeThong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeThong.setText("Hệ thống");
        pnlLeft.add(lblHeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnGioiThieu.setBackground(new java.awt.Color(35, 75, 72));
        btnGioiThieu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/GioiThieu.png"))); // NOI18N
        btnGioiThieu.setText("Giới thiệu");
        btnGioiThieu.setOpaque(true);
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });
        pnlLeft.add(btnGioiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 40));

        btnTrangChu.setBackground(new java.awt.Color(35, 75, 72));
        btnTrangChu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/TrangChu.png"))); // NOI18N
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setOpaque(true);
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        pnlLeft.add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 40));

        btnHuongDan.setBackground(new java.awt.Color(35, 75, 72));
        btnHuongDan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHuongDan.setForeground(new java.awt.Color(255, 255, 255));
        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/HuongDan.png"))); // NOI18N
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setOpaque(true);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        pnlLeft.add(btnHuongDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 40));

        btnQuanLyNhanVien.setBackground(new java.awt.Color(35, 75, 72));
        btnQuanLyNhanVien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/NhanVien.png"))); // NOI18N
        btnQuanLyNhanVien.setText("Quản lý nhân viên");
        btnQuanLyNhanVien.setOpaque(true);
        btnQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhanVienActionPerformed(evt);
            }
        });
        pnlLeft.add(btnQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 40));

        btnQuanLyHocVien.setBackground(new java.awt.Color(35, 75, 72));
        btnQuanLyHocVien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnQuanLyHocVien.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/hocvien.png"))); // NOI18N
        btnQuanLyHocVien.setText("Quản lý học viên");
        btnQuanLyHocVien.setOpaque(true);
        btnQuanLyHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyHocVienActionPerformed(evt);
            }
        });
        pnlLeft.add(btnQuanLyHocVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 40));

        btnQuanLyNguoiHoc.setBackground(new java.awt.Color(35, 75, 72));
        btnQuanLyNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnQuanLyNguoiHoc.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/NguoiHoc.png"))); // NOI18N
        btnQuanLyNguoiHoc.setText("Quản lý người học");
        btnQuanLyNguoiHoc.setOpaque(true);
        btnQuanLyNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNguoiHocActionPerformed(evt);
            }
        });
        pnlLeft.add(btnQuanLyNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 40));

        btnQuanLyKhoaHoc.setBackground(new java.awt.Color(35, 75, 72));
        btnQuanLyKhoaHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnQuanLyKhoaHoc.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/KhoaHoc.png"))); // NOI18N
        btnQuanLyKhoaHoc.setText("Quản lý khóa học");
        btnQuanLyKhoaHoc.setOpaque(true);
        btnQuanLyKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKhoaHocActionPerformed(evt);
            }
        });
        pnlLeft.add(btnQuanLyKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 40));

        btnDoanhThu.setBackground(new java.awt.Color(35, 75, 72));
        btnDoanhThu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        btnDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/DoanhThu.png"))); // NOI18N
        btnDoanhThu.setText("DoanhThu");
        btnDoanhThu.setOpaque(true);
        btnDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoanhThuActionPerformed(evt);
            }
        });
        pnlLeft.add(btnDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 200, 40));

        btnBangDiem.setBackground(new java.awt.Color(35, 75, 72));
        btnBangDiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnBangDiem.setForeground(new java.awt.Color(255, 255, 255));
        btnBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/bangdiem.png"))); // NOI18N
        btnBangDiem.setText("Bảng điểm");
        btnBangDiem.setOpaque(true);
        btnBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangDiemActionPerformed(evt);
            }
        });
        pnlLeft.add(btnBangDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 200, 40));

        btnLuongNguoiHoc.setBackground(new java.awt.Color(35, 75, 72));
        btnLuongNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLuongNguoiHoc.setForeground(new java.awt.Color(255, 255, 255));
        btnLuongNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/luongNguoiHoc.png"))); // NOI18N
        btnLuongNguoiHoc.setText("Lượng người học");
        btnLuongNguoiHoc.setOpaque(true);
        btnLuongNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongNguoiHocActionPerformed(evt);
            }
        });
        pnlLeft.add(btnLuongNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 200, 40));

        btnDiemTheoChuyenDe.setBackground(new java.awt.Color(35, 75, 72));
        btnDiemTheoChuyenDe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDiemTheoChuyenDe.setForeground(new java.awt.Color(255, 255, 255));
        btnDiemTheoChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/diemTheoCD.png"))); // NOI18N
        btnDiemTheoChuyenDe.setText("Điểm chuyên đề");
        btnDiemTheoChuyenDe.setOpaque(true);
        btnDiemTheoChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemTheoChuyenDeActionPerformed(evt);
            }
        });
        pnlLeft.add(btnDiemTheoChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 200, 40));

        btnQuanLyChuyenDe.setBackground(new java.awt.Color(35, 75, 72));
        btnQuanLyChuyenDe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnQuanLyChuyenDe.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/ChuyenDe.png"))); // NOI18N
        btnQuanLyChuyenDe.setText("Quản lý chuyên đề");
        btnQuanLyChuyenDe.setOpaque(true);
        btnQuanLyChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyChuyenDeActionPerformed(evt);
            }
        });
        pnlLeft.add(btnQuanLyChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 200, 40));

        lblQuanLy.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblQuanLy.setForeground(new java.awt.Color(255, 204, 0));
        lblQuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLy.setText("Quản lý");
        pnlLeft.add(lblQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 40));

        lblThongKe.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(255, 204, 0));
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setText("Thống kê");
        pnlLeft.add(lblThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, 40));

        lblBackgroundLeft.setBackground(new java.awt.Color(35, 75, 72));
        lblBackgroundLeft.setOpaque(true);
        pnlLeft.add(lblBackgroundLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 750));

        pnlContainer.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 750));

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setMaximumSize(new java.awt.Dimension(1200, 750));
        pnlRight.setMinimumSize(new java.awt.Dimension(1200, 750));
        pnlRight.setPreferredSize(new java.awt.Dimension(1200, 750));
        pnlRight.setLayout(new java.awt.CardLayout());
        pnlContainer.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        getContentPane().add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
        // TODO add your handling code here:
        selectedButton(btnGioiThieu);
        pnlRight.removeAll();
        pnlRight.add(new PanelGioiThieu(), "cardGioiThieu");
        chuyenPanel("cardGioiThieu");
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        selectedButton(btnTrangChu);
        chuyenPanel("cardTrangChu");
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        // TODO add your handling code here:
        selectedButton(btnHuongDan);
        chuyenPanel("cardHuongDan");
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void btnQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
        selectedButton(btnQuanLyNhanVien);
         pnlRight.removeAll();
        pnlRight.add(new PanelQuanLyNhanVien(), "cardQuanLyNhanVien");
        chuyenPanel("cardQuanLyNhanVien");
    }//GEN-LAST:event_btnQuanLyNhanVienActionPerformed

    private void btnQuanLyHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyHocVienActionPerformed
        // TODO add your handling code here:
        selectedButton(btnQuanLyHocVien);
        chuyenPanel("cardQuanLyHocVien");
    }//GEN-LAST:event_btnQuanLyHocVienActionPerformed

    private void btnQuanLyNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNguoiHocActionPerformed
        // TODO add your handling code here:
        selectedButton(btnQuanLyNguoiHoc);
        chuyenPanel("cardQuanLyNguoiHoc");
    }//GEN-LAST:event_btnQuanLyNguoiHocActionPerformed

    private void btnQuanLyKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKhoaHocActionPerformed
        // TODO add your handling code here:
        selectedButton(btnQuanLyKhoaHoc);
        chuyenPanel("cardQuanlyKhoaHoc");
        updateChuyenDe_KhoaHoc();
    }//GEN-LAST:event_btnQuanLyKhoaHocActionPerformed

    private void btnDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoanhThuActionPerformed
        // TODO add your handling code here:
        selectedButton(btnDoanhThu);
        chuyenPanel("cardDoanhThu");
    }//GEN-LAST:event_btnDoanhThuActionPerformed

    private void btnBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangDiemActionPerformed
        // TODO add your handling code here:
        selectedButton(btnBangDiem);
        chuyenPanel("cardBangDiem");
    }//GEN-LAST:event_btnBangDiemActionPerformed

    private void btnLuongNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongNguoiHocActionPerformed
        // TODO add your handling code here:\
        selectedButton(btnLuongNguoiHoc);
        chuyenPanel("cardLuongNguoiHoc");
    }//GEN-LAST:event_btnLuongNguoiHocActionPerformed

    private void btnDiemTheoChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemTheoChuyenDeActionPerformed
        // TODO add your handling code here:
        selectedButton(btnDiemTheoChuyenDe);
        chuyenPanel("cardDiemTheoChuyenDe");
    }//GEN-LAST:event_btnDiemTheoChuyenDeActionPerformed

    private void btnQuanLyChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyChuyenDeActionPerformed
        // TODO add your handling code here:
        selectedButton(btnQuanLyChuyenDe);
        chuyenPanel("cardQuanLyChuyenDe");

    }//GEN-LAST:event_btnQuanLyChuyenDeActionPerformed

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        // TODO add your handling code here:
        openAccountTool();
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblAccountThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountThoatMouseClicked
        // TODO add your handling code here:

        boolean confirm = MsgBox.confirm(this, "Bạn có chắc muốn thoát không?");
        if (confirm) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblAccountThoatMouseClicked

    private void lblAcountDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcountDangXuatMouseClicked
        // TODO add your handling code here:
        boolean confirm = MsgBox.confirm(this, "Bạn có chắc muốn đăng xuất không?");
        if (confirm) {
            new DangNhap().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_lblAcountDangXuatMouseClicked

    private void lblAccountDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountDoiMatKhauMouseClicked
        // TODO add your handling code here:
        new DoiMatKhau().setVisible(true);
    }//GEN-LAST:event_lblAccountDoiMatKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EduSys_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBangDiem;
    private javax.swing.JToggleButton btnDiemTheoChuyenDe;
    private javax.swing.JToggleButton btnDoanhThu;
    private javax.swing.JToggleButton btnGioiThieu;
    private javax.swing.JToggleButton btnHuongDan;
    private javax.swing.JToggleButton btnLuongNguoiHoc;
    private javax.swing.JToggleButton btnQuanLyChuyenDe;
    private javax.swing.JToggleButton btnQuanLyHocVien;
    private javax.swing.JToggleButton btnQuanLyKhoaHoc;
    private javax.swing.JToggleButton btnQuanLyNguoiHoc;
    private javax.swing.JToggleButton btnQuanLyNhanVien;
    private javax.swing.JToggleButton btnTrangChu;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel lblAccountDoiMatKhau;
    private javax.swing.JLabel lblAccountThoat;
    private javax.swing.JLabel lblAcountDangXuat;
    private javax.swing.JLabel lblBackgroundAccountTool;
    private javax.swing.JLabel lblBackgroundLeft;
    private javax.swing.JLabel lblHeThong;
    private javax.swing.JLabel lblQuanLy;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    // End of variables declaration//GEN-END:variables

    public void openAccountTool() {
        if (accountToolHide == true) {
            ac.jLabelYDown(-60, 50, 20, 5, lblBackgroundAccountTool);
            ac.jLabelYDown(-60, 50, 20, 5, lblAccountDoiMatKhau);
            ac.jLabelYDown(-30, 80, 20, 5, lblAcountDangXuat);
            ac.jLabelYDown(0, 110, 20, 5, lblAccountThoat);
            accountToolHide = false;
        } else {
            ac.jLabelYUp(50, -60, 20, 5, lblBackgroundAccountTool);
            ac.jLabelYUp(50, -60, 20, 5, lblAccountDoiMatKhau);
            ac.jLabelYUp(80, -30, 20, 5, lblAcountDangXuat);
            ac.jLabelYUp(110, 0, 20, 5, lblAccountThoat);
            accountToolHide = true;
        }
    }

    public void addCard() {
        pnlRight.add(new PanelTrangChu(), "cardTrangChu");
        pnlRight.add(new PanelGioiThieu(), "cardGioiThieu");
        pnlRight.add(new PanelHuongDan(), "cardHuongDan");
        pnlRight.add(new PanelQuanLyNhanVien(), "cardQuanLyNhanVien");
        pnlRight.add(new PanelQuanLyHocVien(), "cardQuanLyHocVien");
        pnlRight.add(new PanelQuanLyNguoiHoc(), "cardQuanLyNguoiHoc");
        pnlRight.add(new PanelQuanLyChuyenDe(), "cardQuanLyChuyenDe");
        pnlRight.add(new PanelQuanLyKhoaHoc(), "cardQuanlyKhoaHoc");
        pnlRight.add(new PanelBangDiem(), "cardBangDiem");
        pnlRight.add(new PanelLuongNguoiHoc(), "cardLuongNguoiHoc");
        pnlRight.add(new PanelDiemTheoChuyenDe(), "cardDiemTheoChuyenDe");
        pnlRight.add(new PanelDoanhThu(), "cardDoanhThu");
    }

    public void chuyenPanel(String cardName) {
        layout.show(pnlRight, cardName);
    }

    public void selectedButton(JToggleButton btn) {
        btnTrangChu.setSelected(false);
        btnGioiThieu.setSelected(false);
        btnHuongDan.setSelected(false);
        btnQuanLyChuyenDe.setSelected(false);
        btnQuanLyHocVien.setSelected(false);
        btnQuanLyKhoaHoc.setSelected(false);
        btnQuanLyNguoiHoc.setSelected(false);
        btnQuanLyNhanVien.setSelected(false);
        btnBangDiem.setSelected(false);
        btnLuongNguoiHoc.setSelected(false);
        btnDiemTheoChuyenDe.setSelected(false);
        btnDoanhThu.setSelected(false);
        btn.setSelected(true);
    }

    public void updateChuyenDe_KhoaHoc() {
        PanelQuanLyKhoaHoc kh = new PanelQuanLyKhoaHoc();
        DefaultComboBoxModel model = (DefaultComboBoxModel) kh.getModel();
        model.removeAllElements();
        List<ChuyenDe> list = new ChuyenDeDAO().selectAll();
        for (ChuyenDe cd : list) {
            model.addElement(cd);
        }
    }
}
