/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import AppPackage.AnimationClass;
import com.edusys.dao.ChuyenDeDAO;
import com.edusys.entity.ChuyenDe;
import com.edusys.helper.Auth;
import com.edusys.helper.MsgBox;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.*;
import javax.swing.JToggleButton;

/**
 *
 * @author haotn
 */
public final class EduSys_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form EduSys_JFrame
     */
//    private PanelContainer container = new PanelContainer();
    CardLayout layout;
    AnimationClass ac = new AnimationClass();
    boolean accountToolHide = true;
    String userName = Auth.user.getHoTen();
    String user = Auth.user.getMaNV();

    public EduSys_JFrame() {
        initComponents();
        setLocationRelativeTo(null);
        layout = (CardLayout) pnlRight.getLayout();
        addCard();
        doiMauLabel(lblTrangChu);
        chuyenPanel("cardTrangChu");
        lblUser.setText(user);
        lblUsername.setText("Xin chào " + Auth.user.getHoTen() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblAccountDoiMatKhau = new javax.swing.JLabel();
        lblAccountDangXuat = new javax.swing.JLabel();
        lblAccountThoat = new javax.swing.JLabel();
        lblBackgroundAccountTool = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        lblHeThong = new javax.swing.JLabel();
        lblTrangChu = new javax.swing.JLabel();
        lblHuongDan = new javax.swing.JLabel();
        lblGioiThieu = new javax.swing.JLabel();
        lblQuanLy = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblHocVien = new javax.swing.JLabel();
        lblNguoiHoc = new javax.swing.JLabel();
        lblKhoaHoc = new javax.swing.JLabel();
        lblChuyenDe = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        lblBangDiem = new javax.swing.JLabel();
        lblLuongNguoiHoc = new javax.swing.JLabel();
        lblDiemTheoChuyenDe = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        lblBackgroundLeft = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainer.setMaximumSize(new java.awt.Dimension(1400, 800));
        pnlContainer.setMinimumSize(new java.awt.Dimension(1400, 800));
        pnlContainer.setPreferredSize(new java.awt.Dimension(1400, 800));
        pnlContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setMaximumSize(new java.awt.Dimension(1400, 50));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/user.png"))); // NOI18N
        lblUser.setText("Use: Admin");
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });
        header.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 140, 50));

        jLabel41.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("EduSys");
        header.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        lblUsername.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Version 1.0");
        header.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/header_1.jpg"))); // NOI18N
        header.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 50));

        pnlContainer.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblAccountDoiMatKhau.setBackground(new java.awt.Color(35, 75, 72));
        lblAccountDoiMatKhau.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAccountDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/DoiMatKhau.png"))); // NOI18N
        lblAccountDoiMatKhau.setText("Đổi mật khẩu");
        lblAccountDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccountDoiMatKhauMouseClicked(evt);
            }
        });
        pnlContainer.add(lblAccountDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, -60, 200, 30));

        lblAccountDangXuat.setBackground(new java.awt.Color(35, 75, 72));
        lblAccountDangXuat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAccountDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/DangXuat.png"))); // NOI18N
        lblAccountDangXuat.setText("Đăng xuất");
        lblAccountDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccountDangXuatMouseClicked(evt);
            }
        });
        pnlContainer.add(lblAccountDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, -30, 200, 30));

        lblAccountThoat.setBackground(new java.awt.Color(35, 75, 72));
        lblAccountThoat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAccountThoat.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Thoat.png"))); // NOI18N
        lblAccountThoat.setText("Thoát");
        lblAccountThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccountThoatMouseClicked(evt);
            }
        });
        pnlContainer.add(lblAccountThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 200, 30));

        lblBackgroundAccountTool.setBackground(new java.awt.Color(35, 75, 72));
        lblBackgroundAccountTool.setOpaque(true);
        pnlContainer.add(lblBackgroundAccountTool, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, -60, 200, 90));

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setMaximumSize(new java.awt.Dimension(200, 750));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeThong.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblHeThong.setForeground(new java.awt.Color(255, 204, 0));
        lblHeThong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeThong.setText("Hệ thống");
        pnlLeft.add(lblHeThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        lblTrangChu.setBackground(new java.awt.Color(35, 75, 72));
        lblTrangChu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setText("Trang chủ");
        lblTrangChu.setOpaque(true);
        lblTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTrangChuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTrangChuMousePressed(evt);
            }
        });
        pnlLeft.add(lblTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 40, 190, 40));

        lblHuongDan.setBackground(new java.awt.Color(35, 75, 72));
        lblHuongDan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblHuongDan.setForeground(new java.awt.Color(255, 255, 255));
        lblHuongDan.setText("Hướng dẫn");
        lblHuongDan.setOpaque(true);
        lblHuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHuongDanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHuongDanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHuongDanMousePressed(evt);
            }
        });
        pnlLeft.add(lblHuongDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 190, 40));

        lblGioiThieu.setBackground(new java.awt.Color(35, 75, 72));
        lblGioiThieu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        lblGioiThieu.setText("Giới thiệu");
        lblGioiThieu.setOpaque(true);
        lblGioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGioiThieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGioiThieuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblGioiThieuMousePressed(evt);
            }
        });
        pnlLeft.add(lblGioiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 120, 190, 40));

        lblQuanLy.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblQuanLy.setForeground(new java.awt.Color(255, 204, 0));
        lblQuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLy.setText("Quản lý");
        pnlLeft.add(lblQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 40));

        lblNhanVien.setBackground(new java.awt.Color(35, 75, 72));
        lblNhanVien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblNhanVien.setText("Quản lý nhân viên");
        lblNhanVien.setOpaque(true);
        lblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNhanVienMousePressed(evt);
            }
        });
        pnlLeft.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 200, 190, 40));

        lblHocVien.setBackground(new java.awt.Color(35, 75, 72));
        lblHocVien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblHocVien.setForeground(new java.awt.Color(255, 255, 255));
        lblHocVien.setText("Quản lý học viên");
        lblHocVien.setOpaque(true);
        lblHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHocVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHocVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHocVienMousePressed(evt);
            }
        });
        pnlLeft.add(lblHocVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 240, 190, 40));

        lblNguoiHoc.setBackground(new java.awt.Color(35, 75, 72));
        lblNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblNguoiHoc.setForeground(new java.awt.Color(255, 255, 255));
        lblNguoiHoc.setText("Quản lý người học");
        lblNguoiHoc.setOpaque(true);
        lblNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNguoiHocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNguoiHocMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNguoiHocMousePressed(evt);
            }
        });
        pnlLeft.add(lblNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 280, 190, 40));

        lblKhoaHoc.setBackground(new java.awt.Color(35, 75, 72));
        lblKhoaHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblKhoaHoc.setForeground(new java.awt.Color(255, 255, 255));
        lblKhoaHoc.setText("Quản lý khóa học");
        lblKhoaHoc.setOpaque(true);
        lblKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKhoaHocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKhoaHocMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblKhoaHocMousePressed(evt);
            }
        });
        pnlLeft.add(lblKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 320, 190, 40));

        lblChuyenDe.setBackground(new java.awt.Color(35, 75, 72));
        lblChuyenDe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChuyenDe.setForeground(new java.awt.Color(255, 255, 255));
        lblChuyenDe.setText("Quản lý chuyên đề học");
        lblChuyenDe.setOpaque(true);
        lblChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblChuyenDeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblChuyenDeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblChuyenDeMousePressed(evt);
            }
        });
        pnlLeft.add(lblChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 360, 190, 40));

        lblThongKe.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(255, 204, 0));
        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setText("Thống kê");
        pnlLeft.add(lblThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, 40));

        lblBangDiem.setBackground(new java.awt.Color(35, 75, 72));
        lblBangDiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblBangDiem.setForeground(new java.awt.Color(255, 255, 255));
        lblBangDiem.setText("Bảng điểm");
        lblBangDiem.setOpaque(true);
        lblBangDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBangDiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBangDiemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBangDiemMousePressed(evt);
            }
        });
        pnlLeft.add(lblBangDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 440, 190, 40));

        lblLuongNguoiHoc.setBackground(new java.awt.Color(35, 75, 72));
        lblLuongNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLuongNguoiHoc.setForeground(new java.awt.Color(255, 255, 255));
        lblLuongNguoiHoc.setText("Lượng người học");
        lblLuongNguoiHoc.setOpaque(true);
        lblLuongNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLuongNguoiHocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLuongNguoiHocMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLuongNguoiHocMousePressed(evt);
            }
        });
        pnlLeft.add(lblLuongNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 480, 190, 40));

        lblDiemTheoChuyenDe.setBackground(new java.awt.Color(35, 75, 72));
        lblDiemTheoChuyenDe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDiemTheoChuyenDe.setForeground(new java.awt.Color(255, 255, 255));
        lblDiemTheoChuyenDe.setText("Điểm theo chuyên đề");
        lblDiemTheoChuyenDe.setOpaque(true);
        lblDiemTheoChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDiemTheoChuyenDeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDiemTheoChuyenDeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDiemTheoChuyenDeMousePressed(evt);
            }
        });
        pnlLeft.add(lblDiemTheoChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 520, 190, 40));

        lblDoanhThu.setBackground(new java.awt.Color(35, 75, 72));
        lblDoanhThu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        lblDoanhThu.setText("Doanh thu");
        lblDoanhThu.setOpaque(true);
        lblDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoanhThuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDoanhThuMousePressed(evt);
            }
        });
        pnlLeft.add(lblDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 560, 190, 40));

        lblBackgroundLeft.setBackground(new java.awt.Color(35, 75, 72));
        lblBackgroundLeft.setOpaque(true);
        pnlLeft.add(lblBackgroundLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 750));

        pnlContainer.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 750));

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setMaximumSize(new java.awt.Dimension(1200, 750));
        pnlRight.setMinimumSize(new java.awt.Dimension(1200, 750));
        pnlRight.setPreferredSize(new java.awt.Dimension(1200, 750));
        pnlRight.setLayout(new java.awt.CardLayout());
        pnlContainer.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        getContentPane().add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        // TODO add your handling code here:
        openAccountTool();
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblAccountThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountThoatMouseClicked
        // TODO add your handling code here:

        boolean confirm = MsgBox.confirm(this, "Bạn có chắc muốn thoát không?");
        if (confirm) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblAccountThoatMouseClicked

    private void lblAccountDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountDangXuatMouseClicked
        // TODO add your handling code here:
        boolean confirm = MsgBox.confirm(this, "Bạn có chắc muốn đăng xuất không?");
        if (confirm) {
            new DangNhap().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_lblAccountDangXuatMouseClicked

    private void lblAccountDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccountDoiMatKhauMouseClicked
        // TODO add your handling code here:
        new DoiMatKhau().setVisible(true);
    }//GEN-LAST:event_lblAccountDoiMatKhauMouseClicked

    private void lblTrangChuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblTrangChu);
        chuyenPanel("cardTrangChu");
    }//GEN-LAST:event_lblTrangChuMousePressed

    private void lblHuongDanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongDanMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblHuongDan);
        chuyenPanel("cardHuongDan");
    }//GEN-LAST:event_lblHuongDanMousePressed

    private void lblGioiThieuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiThieuMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblGioiThieu);
        chuyenPanel("cardGioiThieu");
    }//GEN-LAST:event_lblGioiThieuMousePressed

    private void lblNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblNhanVien);
        chuyenPanel("cardNhanVien");
    }//GEN-LAST:event_lblNhanVienMousePressed

    private void lblHocVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHocVienMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblHocVien);
        chuyenPanel("cardHocVien");
    }//GEN-LAST:event_lblHocVienMousePressed

    private void lblNguoiHocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiHocMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblNguoiHoc);
        chuyenPanel("cardNguoiHoc");
    }//GEN-LAST:event_lblNguoiHocMousePressed

    private void lblKhoaHocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoaHocMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblKhoaHoc);
        chuyenPanel("cardKhoaHoc");
    }//GEN-LAST:event_lblKhoaHocMousePressed

    private void lblChuyenDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChuyenDeMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblChuyenDe);
        chuyenPanel("cardChuyenDe");
    }//GEN-LAST:event_lblChuyenDeMousePressed

    private void lblBangDiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBangDiemMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblBangDiem);
        chuyenPanel("cardBangDiem");
    }//GEN-LAST:event_lblBangDiemMousePressed

    private void lblLuongNguoiHocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLuongNguoiHocMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblLuongNguoiHoc);
        chuyenPanel("cardLuongNguoiHoc");
    }//GEN-LAST:event_lblLuongNguoiHocMousePressed

    private void lblDiemTheoChuyenDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiemTheoChuyenDeMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblDiemTheoChuyenDe);
        chuyenPanel("cardDiemTheoChuyenDe");
    }//GEN-LAST:event_lblDiemTheoChuyenDeMousePressed

    private void lblDoanhThuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuMousePressed
        // TODO add your handling code here:
        doiMauLabel(lblDoanhThu);
        chuyenPanel("cardDoanhThu");
    }//GEN-LAST:event_lblDoanhThuMousePressed

    private void lblTrangChuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblTrangChu);
    }//GEN-LAST:event_lblTrangChuMouseEntered

    private void lblHuongDanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongDanMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblHuongDan);
    }//GEN-LAST:event_lblHuongDanMouseEntered

    private void lblGioiThieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiThieuMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblGioiThieu);
    }//GEN-LAST:event_lblGioiThieuMouseEntered

    private void lblNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblNhanVien);
    }//GEN-LAST:event_lblNhanVienMouseEntered

    private void lblHocVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHocVienMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblHocVien);
    }//GEN-LAST:event_lblHocVienMouseEntered

    private void lblNguoiHocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiHocMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblNguoiHoc);
    }//GEN-LAST:event_lblNguoiHocMouseEntered

    private void lblKhoaHocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoaHocMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblKhoaHoc);
    }//GEN-LAST:event_lblKhoaHocMouseEntered

    private void lblChuyenDeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChuyenDeMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblChuyenDe);
    }//GEN-LAST:event_lblChuyenDeMouseEntered

    private void lblBangDiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBangDiemMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblBangDiem);
    }//GEN-LAST:event_lblBangDiemMouseEntered

    private void lblLuongNguoiHocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLuongNguoiHocMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblLuongNguoiHoc);
    }//GEN-LAST:event_lblLuongNguoiHocMouseEntered

    private void lblDiemTheoChuyenDeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiemTheoChuyenDeMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblDiemTheoChuyenDe);
    }//GEN-LAST:event_lblDiemTheoChuyenDeMouseEntered

    private void lblDoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuMouseEntered
        // TODO add your handling code here:
        mouseEnter(lblDoanhThu);
    }//GEN-LAST:event_lblDoanhThuMouseEntered

    private void lblTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrangChuMouseExited
        // TODO add your handling code here:
        mouseExit(lblTrangChu);
    }//GEN-LAST:event_lblTrangChuMouseExited

    private void lblHuongDanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongDanMouseExited
        // TODO add your handling code here:
        mouseExit(lblHuongDan);
    }//GEN-LAST:event_lblHuongDanMouseExited

    private void lblGioiThieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiThieuMouseExited
        // TODO add your handling code here:
        mouseExit(lblGioiThieu);
    }//GEN-LAST:event_lblGioiThieuMouseExited

    private void lblNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseExited
        // TODO add your handling code here:
        mouseExit(lblNhanVien);
    }//GEN-LAST:event_lblNhanVienMouseExited

    private void lblHocVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHocVienMouseExited
        // TODO add your handling code here:
        mouseExit(lblHocVien);
    }//GEN-LAST:event_lblHocVienMouseExited

    private void lblNguoiHocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiHocMouseExited
        // TODO add your handling code here:
        mouseExit(lblNguoiHoc);
    }//GEN-LAST:event_lblNguoiHocMouseExited

    private void lblKhoaHocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoaHocMouseExited
        // TODO add your handling code here:
        mouseExit(lblKhoaHoc);
    }//GEN-LAST:event_lblKhoaHocMouseExited

    private void lblChuyenDeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChuyenDeMouseExited
        // TODO add your handling code here:
        mouseExit(lblChuyenDe);
    }//GEN-LAST:event_lblChuyenDeMouseExited

    private void lblBangDiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBangDiemMouseExited
        // TODO add your handling code here:
        mouseExit(lblBangDiem);
    }//GEN-LAST:event_lblBangDiemMouseExited

    private void lblLuongNguoiHocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLuongNguoiHocMouseExited
        // TODO add your handling code here:
        mouseExit(lblLuongNguoiHoc);
    }//GEN-LAST:event_lblLuongNguoiHocMouseExited

    private void lblDiemTheoChuyenDeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiemTheoChuyenDeMouseExited
        // TODO add your handling code here:
        mouseExit(lblDiemTheoChuyenDe);
    }//GEN-LAST:event_lblDiemTheoChuyenDeMouseExited

    private void lblDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuMouseExited
        // TODO add your handling code here:
        mouseExit(lblDoanhThu);
    }//GEN-LAST:event_lblDoanhThuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EduSys_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EduSys_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel lblAccountDangXuat;
    private javax.swing.JLabel lblAccountDoiMatKhau;
    private javax.swing.JLabel lblAccountThoat;
    private javax.swing.JLabel lblBackgroundAccountTool;
    private javax.swing.JLabel lblBackgroundLeft;
    private javax.swing.JLabel lblBangDiem;
    private javax.swing.JLabel lblChuyenDe;
    private javax.swing.JLabel lblDiemTheoChuyenDe;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblGioiThieu;
    private javax.swing.JLabel lblHeThong;
    private javax.swing.JLabel lblHocVien;
    private javax.swing.JLabel lblHuongDan;
    private javax.swing.JLabel lblKhoaHoc;
    private javax.swing.JLabel lblLuongNguoiHoc;
    private javax.swing.JLabel lblNguoiHoc;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblQuanLy;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    // End of variables declaration//GEN-END:variables

    public void openAccountTool() {
        if (accountToolHide == true) {
            ac.jLabelYDown(-60, 50, 20, 5, lblBackgroundAccountTool);
            ac.jLabelYDown(-60, 50, 20, 5, lblAccountDoiMatKhau);
            ac.jLabelYDown(-30, 80, 20, 5, lblAccountDangXuat);
            ac.jLabelYDown(0, 110, 20, 5, lblAccountThoat);
            accountToolHide = false;
        } else {
            ac.jLabelYUp(50, -60, 20, 5, lblBackgroundAccountTool);
            ac.jLabelYUp(50, -60, 20, 5, lblAccountDoiMatKhau);
            ac.jLabelYUp(80, -30, 20, 5, lblAccountDangXuat);
            ac.jLabelYUp(110, 0, 20, 5, lblAccountThoat);
            accountToolHide = true;
        }
    }

    public void addCard() {
        pnlRight.add(new PanelTrangChu(), "cardTrangChu");
        pnlRight.add(new PanelGioiThieu(), "cardGioiThieu");
        pnlRight.add(new PanelHuongDan(), "cardHuongDan");
        pnlRight.add(new PanelQuanLyNhanVien(), "cardNhanVien");
        pnlRight.add(new PanelQuanLyHocVien(), "cardHocVien");
        pnlRight.add(new PanelQuanLyNguoiHoc(), "cardNguoiHoc");
        pnlRight.add(new PanelQuanLyChuyenDe(), "cardChuyenDe");
        pnlRight.add(new PanelQuanLyKhoaHoc(), "cardKhoaHoc");
        pnlRight.add(new PanelBangDiem(), "cardBangDiem");
        pnlRight.add(new PanelLuongNguoiHoc(), "cardLuongNguoiHoc");
        pnlRight.add(new PanelDiemTheoChuyenDe(), "cardDiemTheoChuyenDe");
        pnlRight.add(new PanelDoanhThu(), "cardDoanhThu");
    }

    public void chuyenPanel(String cardName) {
        layout.show(pnlRight, cardName);
    }

    public void doiMauLabel(JLabel lbl) {
        lblTrangChu.setBackground(new Color(36, 75, 72));
        lblGioiThieu.setBackground(new Color(36, 75, 72));
        lblHuongDan.setBackground(new Color(36, 75, 72));
        lblNhanVien.setBackground(new Color(36, 75, 72));
        lblChuyenDe.setBackground(new Color(36, 75, 72));
        lblHocVien.setBackground(new Color(36, 75, 72));
        lblNguoiHoc.setBackground(new Color(36, 75, 72));
        lblKhoaHoc.setBackground(new Color(36, 75, 72));
        lblBangDiem.setBackground(new Color(36, 75, 72));
        lblDiemTheoChuyenDe.setBackground(new Color(36, 75, 72));
        lblLuongNguoiHoc.setBackground(new Color(36, 75, 72));
        lblDoanhThu.setBackground(new Color(36, 75, 72));
        lbl.setBackground(new Color(102, 102, 102));
//        lblAccountDoiMatKhau.setBackground(new Color(36, 75, 72));
//        lblAccountDangXuat.setBackground(new Color(36, 75, 72));
//        lblAccountThoat.setBackground(new Color(36, 75, 72));
//        if (lbl.getText().equals("Thoát")) {
//        } else {
//            lbl.setBackground(new Color(102, 102, 102));
//        }
        //lbl.setOpaque(true);
    }

    public void mouseEnter(JLabel lbl) {
        lbl.setForeground(new Color(0, 204, 153));
    }

    public void mouseExit(JLabel lbl) {
        lbl.setForeground(Color.WHITE);
    }

//    public void selectedButton(JToggleButton btn) {
//        btnTrangChu.setSelected(false);
//        btnGioiThieu.setSelected(false);
//        btnHuongDan.setSelected(false);
//        btnChuyenDe.setSelected(false);
//        btnHocVien.setSelected(false);
//        btnKhoaHoc.setSelected(false);
//        btnNguoiHoc.setSelected(false);
//        btnNhanVien.setSelected(false);
//        btnBangDiem.setSelected(false);
//        btnLuongNguoiHoc.setSelected(false);
//        btnDiemTheoChuyenDe.setSelected(false);
//        btnDoanhThu.setSelected(false);
//        btn.setSelected(true);
//    }
}
