/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import AppPackage.AnimationClass;

/**
 *
 * @author haotn
 */
public class PanelTrangChu extends javax.swing.JPanel {

    /**
     * Creates new form PanelTrangChu
     */
    AnimationClass ac = new AnimationClass();

    public PanelTrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSlideShow = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblImg1 = new javax.swing.JLabel();
        lblImg2 = new javax.swing.JLabel();
        lblImg3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSlideShow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("EduSys");
        pnlSlideShow.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 325, 300, 100));

        lblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/SlideShow1.png"))); // NOI18N
        pnlSlideShow.add(lblImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 750));

        lblImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/SlideShow2.png"))); // NOI18N
        pnlSlideShow.add(lblImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 1200, 750));

        lblImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/SlideShow3.png"))); // NOI18N
        pnlSlideShow.add(lblImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2400, 0, 1200, 750));

        add(pnlSlideShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblImg3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlSlideShow;
    // End of variables declaration//GEN-END:variables
    public void slideshow() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                int nb = 0;
                try {
                    while (true) {
                        switch (nb) {
                            case 0:
                                Thread.sleep(5000);
                                ac.jLabelXLeft(0, -1200, 12, 10, lblImg1);
                                ac.jLabelXLeft(1200, 0, 12, 10, lblImg2);
                                ac.jLabelXLeft(2400, 1200, 12, 10, lblImg3);
                                nb++;
                            case 1:
                                Thread.sleep(5000);
                                ac.jLabelXLeft(-1200, -2400, 12, 10, lblImg1);
                                ac.jLabelXLeft(0, -1200, 12, 10, lblImg2);
                                ac.jLabelXLeft(1200, 0, 12, 10, lblImg3);
                                nb++;
                            case 2:
                                Thread.sleep(5000);
                                ac.jLabelXRight(-2400, -1200, 12, 10, lblImg1);
                                ac.jLabelXRight(-1200, 0, 12, 10, lblImg2);
                                ac.jLabelXRight(0, 1200, 12, 10, lblImg3);
                                nb++;
                            case 3:
                                Thread.sleep(5000);
                                ac.jLabelXRight(-1200, 0, 12, 10, lblImg1);
                                ac.jLabelXRight(0, 1200, 12, 10, lblImg2);
                                ac.jLabelXRight(1200, 2400, 12, 10, lblImg3);
                                nb = 0;
                        }
                    }
                } catch (Exception e) {
                }
            }

        }).start();
    }
}
