/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.ChuyenDeDAO;
import com.edusys.dao.HocVienDAO;
import com.edusys.dao.KhoaHocDAO;
import com.edusys.dao.NguoiHocDAO;
import com.edusys.entity.ChuyenDe;
import com.edusys.entity.HocVien;
import com.edusys.entity.KhoaHoc;
import com.edusys.entity.NguoiHoc;
import com.edusys.helper.Auth;
import com.edusys.helper.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author haotn
 */
public class PanelQuanLyHocVien extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyHocVien
     */
    DefaultTableModel modelNH;
    DefaultTableModel modelHV;
    JTableHeader header;
    DefaultComboBoxModel modelCboChuyenDe = new DefaultComboBoxModel();
    DefaultComboBoxModel modelCboKhoaHoc = new DefaultComboBoxModel();

    public PanelQuanLyHocVien() {
        initComponents();
        setModelTableNguoiHoc();
        setModelTableHocVien();
        cboLocChuyenDe.setModel(modelCboChuyenDe);
        cboLocKhoaHoc.setModel(modelCboKhoaHoc);
        fillComboBoxChuyenDe();
        fillComboBoxKhoaHoc();
        fillTableHocVien();
        fillTableNguoiHoc();
    }

    public void setModelTableNguoiHoc() {
        modelNH = new DefaultTableModel(new Object[][]{}, new Object[]{"Mã NH", "Họ và tên", "Giới tính", "Ngày sinh", "Điện thoại", "Email", "Ghi chú"});
        tblNguoiHoc.setModel(modelNH);
        header = tblNguoiHoc.getTableHeader();
        header.setForeground(new Color(102, 102, 102));
        header.setFont(new Font("SansSerif", 1, 18));
    }

    public void setModelTableHocVien() {
        modelHV = new DefaultTableModel(new Object[][]{}, new Object[]{"Mã học viên", "Mã người học", "Mã khóa học", "Họ và tên", "Điểm"});
        tblHocVien.setModel(modelHV);
        header = tblHocVien.getTableHeader();
        header.setForeground(new Color(102, 102, 102));
        header.setFont(new Font("SansSerif", 1, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblHocVien = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNguoiHoc = new javax.swing.JTable();
        pnlLocHocVien = new javax.swing.JPanel();
        lblLocChuyenDe = new javax.swing.JLabel();
        cboLocChuyenDe = new javax.swing.JComboBox<>();
        lblLocKhoaHoc = new javax.swing.JLabel();
        cboLocKhoaHoc = new javax.swing.JComboBox<>();
        txtTimHocVien = new javax.swing.JTextField();
        btnThemVaoKhoaHoc = new javax.swing.JButton();
        txtTimNguoiHoc = new javax.swing.JTextField();
        btnXoaKhoiKhoaHoc = new javax.swing.JButton();
        btnCapNhatDiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblHocVien.setAutoCreateRowSorter(true);
        tblHocVien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHocVien.setGridColor(new java.awt.Color(255, 255, 255));
        tblHocVien.setName(""); // NOI18N
        tblHocVien.setRowHeight(30);
        jScrollPane2.setViewportView(tblHocVien);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 250));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblNguoiHoc.setAutoCreateRowSorter(true);
        tblNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNguoiHoc.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tblNguoiHoc);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1200, 250));

        pnlLocHocVien.setBackground(new java.awt.Color(255, 255, 255));
        pnlLocHocVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLocChuyenDe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLocChuyenDe.setForeground(new java.awt.Color(153, 153, 153));
        lblLocChuyenDe.setText("Chuyên đề");
        pnlLocHocVien.add(lblLocChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 20));

        cboLocChuyenDe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cboLocChuyenDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLocChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocChuyenDeActionPerformed(evt);
            }
        });
        pnlLocHocVien.add(cboLocChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 300, -1));

        lblLocKhoaHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLocKhoaHoc.setForeground(new java.awt.Color(153, 153, 153));
        lblLocKhoaHoc.setText("Khóa học");
        pnlLocHocVien.add(lblLocKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        cboLocKhoaHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cboLocKhoaHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLocKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocKhoaHocActionPerformed(evt);
            }
        });
        pnlLocHocVien.add(cboLocKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 300, -1));

        txtTimHocVien.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTimHocVien.setForeground(new java.awt.Color(153, 153, 153));
        txtTimHocVien.setText("Tìm kiếm học viên");
        txtTimHocVien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimHocVienFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimHocVienFocusLost(evt);
            }
        });
        txtTimHocVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimHocVienKeyReleased(evt);
            }
        });
        pnlLocHocVien.add(txtTimHocVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, -1));

        add(pnlLocHocVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 40));

        btnThemVaoKhoaHoc.setBackground(new java.awt.Color(255, 255, 255));
        btnThemVaoKhoaHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThemVaoKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/add.png"))); // NOI18N
        btnThemVaoKhoaHoc.setText("Thêm vào khóa học");
        btnThemVaoKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoKhoaHocActionPerformed(evt);
            }
        });
        add(btnThemVaoKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 710, -1, -1));

        txtTimNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTimNguoiHoc.setForeground(new java.awt.Color(153, 153, 153));
        txtTimNguoiHoc.setText("Tìm kiếm người học");
        txtTimNguoiHoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimNguoiHocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimNguoiHocFocusLost(evt);
            }
        });
        txtTimNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimNguoiHocActionPerformed(evt);
            }
        });
        txtTimNguoiHoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimNguoiHocKeyReleased(evt);
            }
        });
        add(txtTimNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 250, -1));

        btnXoaKhoiKhoaHoc.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaKhoiKhoaHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXoaKhoiKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Delete.png"))); // NOI18N
        btnXoaKhoiKhoaHoc.setText("Xóa khỏi khóa học");
        btnXoaKhoiKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKhoiKhoaHocActionPerformed(evt);
            }
        });
        add(btnXoaKhoiKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, -1, -1));

        btnCapNhatDiem.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhatDiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCapNhatDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Edit.png"))); // NOI18N
        btnCapNhatDiem.setText("Cập nhật điểm");
        btnCapNhatDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatDiemActionPerformed(evt);
            }
        });
        add(btnCapNhatDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Người học");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Học viên");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimNguoiHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimNguoiHocActionPerformed

    private void btnThemVaoKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoKhoaHocActionPerformed
        // TODO add your handling code here:
        addHocVien();
    }//GEN-LAST:event_btnThemVaoKhoaHocActionPerformed

    private void txtTimHocVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimHocVienKeyReleased
        // TODO add your handling code here:
        fillTableHocVien();
    }//GEN-LAST:event_txtTimHocVienKeyReleased

    private void txtTimHocVienFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimHocVienFocusGained
        // TODO add your handling code here:
        focusGained(txtTimHocVien, "Tìm kiếm học viên");
    }//GEN-LAST:event_txtTimHocVienFocusGained

    private void txtTimHocVienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimHocVienFocusLost
        // TODO add your handling code here:
        focusLost(txtTimHocVien, "Tìm kiếm học viên");
    }//GEN-LAST:event_txtTimHocVienFocusLost

    private void cboLocKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocKhoaHocActionPerformed
        // TODO add your handling code here:
        fillTableHocVien();
    }//GEN-LAST:event_cboLocKhoaHocActionPerformed

    private void cboLocChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocChuyenDeActionPerformed
        // TODO add your handling code here:
        fillTableHocVien();
    }//GEN-LAST:event_cboLocChuyenDeActionPerformed

    private void txtTimNguoiHocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimNguoiHocFocusGained
        // TODO add your handling code here:
        focusGained(txtTimNguoiHoc, "Tìm kiếm người học");
    }//GEN-LAST:event_txtTimNguoiHocFocusGained

    private void txtTimNguoiHocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimNguoiHocFocusLost
        // TODO add your handling code here:
        focusLost(txtTimNguoiHoc, "Tìm kiếm người học");
    }//GEN-LAST:event_txtTimNguoiHocFocusLost

    private void txtTimNguoiHocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimNguoiHocKeyReleased
        // TODO add your handling code here:
        fillTableNguoiHoc();
    }//GEN-LAST:event_txtTimNguoiHocKeyReleased

    private void btnXoaKhoiKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhoiKhoaHocActionPerformed
        // TODO add your handling code here:
        removeHocVien();
    }//GEN-LAST:event_btnXoaKhoiKhoaHocActionPerformed

    private void btnCapNhatDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatDiemActionPerformed
        // TODO add your handling code here:
        updateDiem();
    }//GEN-LAST:event_btnCapNhatDiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatDiem;
    private javax.swing.JButton btnThemVaoKhoaHoc;
    private javax.swing.JButton btnXoaKhoiKhoaHoc;
    private javax.swing.JComboBox<String> cboLocChuyenDe;
    private javax.swing.JComboBox<String> cboLocKhoaHoc;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLocChuyenDe;
    private javax.swing.JLabel lblLocKhoaHoc;
    private javax.swing.JPanel pnlLocHocVien;
    private javax.swing.JTable tblHocVien;
    private javax.swing.JTable tblNguoiHoc;
    private javax.swing.JTextField txtTimHocVien;
    private javax.swing.JTextField txtTimNguoiHoc;
    // End of variables declaration//GEN-END:variables

    ChuyenDeDAO cddao = new ChuyenDeDAO();
    KhoaHocDAO khdao = new KhoaHocDAO();
    NguoiHocDAO nhdao = new NguoiHocDAO();
    HocVienDAO hvdao = new HocVienDAO();

    public void focusGained(JTextField txt, String text) {
        if (txt.getText().equals(text)) {
            txt.setText("");
        }
        txt.setForeground(Color.black);
    }

    public void focusLost(JTextField txt, String text) {
        if (txt.getText().equals("")) {
            txt.setText(text);
            txt.setForeground(new Color(102, 102, 102));
        }

    }

    public void init() {
        fillComboBoxChuyenDe();
    }

    public void fillComboBoxChuyenDe() {
        modelCboChuyenDe.removeAllElements();
        List<ChuyenDe> list = cddao.selectAll();
        for (ChuyenDe cd : list) {
            modelCboChuyenDe.addElement(cd);
        }
        fillComboBoxKhoaHoc();
    }

    public void fillComboBoxKhoaHoc() {
        modelCboKhoaHoc.removeAllElements();
        ChuyenDe chuyenDe = (ChuyenDe) cboLocChuyenDe.getSelectedItem();
        if (chuyenDe != null) {
            List<KhoaHoc> list = khdao.selectByChuyenDe(chuyenDe.getMaCD());
            for (KhoaHoc kh : list) {
                modelCboKhoaHoc.addElement(kh);
            }
            fillTableHocVien();
        }
    }

    public void fillTableHocVien() {
        modelHV.setRowCount(0);
        KhoaHoc khoaHoc = (KhoaHoc) cboLocKhoaHoc.getSelectedItem();
        if (khoaHoc != null) {
            List<HocVien> list;
//            if (txtTimHocVien.getText().equals("") || txtTimHocVien.getText().equals("Tìm kiếm học viên")) {
//                list = hvdao.selectByKeyWord(txtTimHocVien.getText(), khoaHoc);
//            } else {
            list = hvdao.selectByKhoaHoc(khoaHoc.getMaKH());
//            }
            for (int i = 0; i < list.size(); i++) {
                HocVien hv = list.get(i);
                String hoTen = nhdao.selectById(hv.getMaNH()).getHo() + " " + nhdao.selectById(hv.getMaNH()).getTen();
                modelHV.addRow(new Object[]{hv.getMaHV(), hv.getMaNH(), hv.getMaKH(), hoTen, hv.getDiem()});
            }
            fillTableNguoiHoc();
        }
    }

    public void fillTableNguoiHoc() {
        modelNH.setRowCount(0);
        KhoaHoc khoaHoc = (KhoaHoc) cboLocKhoaHoc.getSelectedItem();
        String keyWord = txtTimNguoiHoc.getText();
        List<NguoiHoc> list;
        if (keyWord.trim().equals("") || keyWord.trim().equals("Tìm kiếm người học")) {
            list = nhdao.selectNotlnCourse(khoaHoc.getMaKH());
        } else {
            list = nhdao.selectByKeyWordAndNotInCourse(khoaHoc.getMaKH(), keyWord);
        }

        for (NguoiHoc nh : list) {
            modelNH.addRow(new Object[]{
                nh.getMaNH(), nh.getHo() + " " + nh.getTen(), nh.getGioiTinh() ? "Nam" : "Nữ", nh.getNgaySinh(), nh.getDienThoai(), nh.getEmail()
            });
        }
    }

    public void addHocVien() {
        KhoaHoc khoaHoc = (KhoaHoc) cboLocKhoaHoc.getSelectedItem();
        for (int row : tblNguoiHoc.getSelectedRows()) {
            HocVien hv = new HocVien();
            hv.setMaKH(khoaHoc.getMaKH());
            hv.setDiem(0);
            hv.setMaNH((String) tblNguoiHoc.getValueAt(row, 0));
            hvdao.insert(hv);
        }
        fillTableHocVien();
    }

    public void removeHocVien() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa học viên ");
        } else {
            boolean confirm = MsgBox.confirm(this, "Are you sure delete ?");
            if (confirm) {
                for (int row : tblHocVien.getSelectedRows()) {
                    int maHV = Integer.parseInt(String.valueOf(tblHocVien.getValueAt(row, 0)));
                    hvdao.delete(maHV);
                }
                fillTableHocVien();
            }
        }
    }

    public void updateDiem() {
        for (int i = 0; i < tblHocVien.getRowCount(); i++) {
            int maHV = (Integer) tblHocVien.getValueAt(i, 0);
            HocVien hv = hvdao.selectById(maHV);
            hv.setDiem(Double.parseDouble(String.valueOf(tblHocVien.getValueAt(i, 4))));
            hvdao.update(hv);

        }
        MsgBox.alert(this, "Cập nhật điểm thành công");
    }

}
