/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.ChuyenDeDAO;
import com.edusys.entity.ChuyenDe;
import com.edusys.helper.*;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author haotn
 */
public class PanelQuanLyChuyenDe extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyChuyenDe
     */
    DefaultTableModel model;
    JTableHeader header;

    public PanelQuanLyChuyenDe() {
        initComponents();
        setModelTable();
        fillTable();
    }

    public void setModelTable() {
        model = new DefaultTableModel(new Object[][]{}, new Object[]{"Mã chuyên đề", "Tên chuyên đề", "Học phí", "Thời lượng", "Mô tả", "Ảnh"});
        tblChuyenDe.setModel(model);
        header = tblChuyenDe.getTableHeader();
        header.setForeground(new Color(102, 102, 102));
        header.setFont(new Font("SansSerif", 1, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblChuyenDe = new javax.swing.JTable();
        txtTimCD = new javax.swing.JTextField();
        pnlFormChuyenDe = new javax.swing.JPanel();
        lblLogoChuyenDe = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtTenChuyenDe = new javax.swing.JTextField();
        txtThoiLuong = new javax.swing.JTextField();
        txtMaChuyenDe = new javax.swing.JTextField();
        txtHocPhi = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnLamMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        pnlCongCuBangChuyenDe = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Chuyên đề");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jScrollPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblChuyenDe.setAutoCreateRowSorter(true);
        tblChuyenDe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblChuyenDe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChuyenDe.setGridColor(new java.awt.Color(255, 255, 255));
        tblChuyenDe.setRowHeight(30);
        tblChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChuyenDeMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblChuyenDe);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 250));

        txtTimCD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTimCD.setForeground(new java.awt.Color(153, 153, 153));
        txtTimCD.setText("Tìm kiếm chuyên đề");
        add(txtTimCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 250, -1));

        pnlFormChuyenDe.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormChuyenDe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoChuyenDe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblLogoChuyenDe.setOpaque(true);
        lblLogoChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoChuyenDeMouseClicked(evt);
            }
        });
        pnlFormChuyenDe.add(lblLogoChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 250));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Mô tả");
        pnlFormChuyenDe.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Mã chuyên đề");
        pnlFormChuyenDe.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Tên chuyên đề");
        pnlFormChuyenDe.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Học phí");
        pnlFormChuyenDe.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Thời lượng");
        pnlFormChuyenDe.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, -1));

        txtTenChuyenDe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormChuyenDe.add(txtTenChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 300, -1));

        txtThoiLuong.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormChuyenDe.add(txtThoiLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 100, -1));

        txtMaChuyenDe.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormChuyenDe.add(txtMaChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 100, -1));

        txtHocPhi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormChuyenDe.add(txtHocPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 150, -1));

        txtMoTa.setColumns(20);
        txtMoTa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtMoTa.setRows(5);
        jScrollPane7.setViewportView(txtMoTa);

        pnlFormChuyenDe.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 770, 140));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(102, 102, 102));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Update.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlFormChuyenDe.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(102, 102, 102));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Edit.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        pnlFormChuyenDe.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(102, 102, 102));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlFormChuyenDe.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(102, 102, 102));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlFormChuyenDe.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        add(pnlFormChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1200, 350));

        pnlCongCuBangChuyenDe.setBackground(new java.awt.Color(255, 255, 255));
        pnlCongCuBangChuyenDe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLast.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLast.setForeground(new java.awt.Color(102, 102, 102));
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlCongCuBangChuyenDe.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        btnFirst.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(102, 102, 102));
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlCongCuBangChuyenDe.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        btnPrev.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(102, 102, 102));
        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlCongCuBangChuyenDe.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        btnNext.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(102, 102, 102));
        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlCongCuBangChuyenDe.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        add(pnlCongCuBangChuyenDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1200, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        isUpdate = false;
        if (check()) {
            insert();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        isUpdate = true;
        if (check()) {
            update();

        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void lblLogoChuyenDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoChuyenDeMouseClicked
        // TODO add your handling code here:
        chonAnh();
    }//GEN-LAST:event_lblLogoChuyenDeMouseClicked

    private void tblChuyenDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChuyenDeMouseClicked
        // TODO add your handling code here:
        index = tblChuyenDe.getSelectedRow();
        edit();
    }//GEN-LAST:event_tblChuyenDeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblLogoChuyenDe;
    private javax.swing.JPanel pnlCongCuBangChuyenDe;
    private javax.swing.JPanel pnlFormChuyenDe;
    private javax.swing.JTable tblChuyenDe;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtMaChuyenDe;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenChuyenDe;
    private javax.swing.JTextField txtThoiLuong;
    private javax.swing.JTextField txtTimCD;
    // End of variables declaration//GEN-END:variables

    JFileChooser filenChooser = new JFileChooser();
    ChuyenDeDAO dao = new ChuyenDeDAO();
    int index = 0;
    boolean isUpdate = false;

    void chonAnh() {
        if (filenChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = filenChooser.getSelectedFile();
            XImage.save(file);
            ImageIcon icon = XImage.read(file.getName());
            lblLogoChuyenDe.setIcon(icon);
            lblLogoChuyenDe.setToolTipText(file.getName());
        }
    }

    void fillTable() {
        //DefaultTableModel model = (DefaultTableModel) tblChuyenDe.getModel();
        model.setRowCount(0);

        try {
            List<ChuyenDe> list = dao.selectAll();
            for (ChuyenDe cd : list) {
                Object[] row = {
                    cd.getMaCD(),
                    cd.getTenCD(),
                    cd.getHocPhi(),
                    cd.getThoiLuong(),
                    cd.getMoTa(),
                    cd.getHinhCD()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void setForm(ChuyenDe cd) {
        txtMaChuyenDe.setText(cd.getMaCD());
        txtTenChuyenDe.setText(cd.getTenCD());
        txtHocPhi.setText(String.valueOf(cd.getHocPhi()));
        txtThoiLuong.setText(String.valueOf(cd.getThoiLuong()));
        lblLogoChuyenDe.setToolTipText(cd.getHinhCD());
        if (cd.getHinhCD() != null) {
            lblLogoChuyenDe.setIcon(XImage.read(cd.getHinhCD()));
        }
        txtMoTa.setText(cd.getMoTa());
    }

    ChuyenDe getForm() {
        ChuyenDe cd = new ChuyenDe();
        cd.setMaCD(txtMaChuyenDe.getText());
        cd.setTenCD(txtTenChuyenDe.getText());
        cd.setHocPhi(Float.valueOf(txtHocPhi.getText()));
        cd.setThoiLuong(Integer.valueOf(txtThoiLuong.getText()));
        cd.setHinhCD(lblLogoChuyenDe.getToolTipText());
        cd.setMoTa(txtMoTa.getText());
        return cd;
    }

    void edit() {
        try {
            String macd = (String) tblChuyenDe.getValueAt(this.index, 0);
            ChuyenDe model = dao.selectById(macd);
            if (model != null) {
                setForm(model);//lỗi chưa bk sửa
                this.updateStatus();
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void insert() {
        ChuyenDe model = getForm();
        if (model.getHinhCD() == null) {
            MsgBox.alert(this, "Hình Không Được Để Trống");
            return;
        }
        try {
            dao.insert(model);
            this.fillTable();
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    void update() {
        ChuyenDe model = getForm();
        if (MsgBox.confirm(this, "Bạn có chắc muốn cập nhật chuyên đề này không?")) {
            try {
                dao.update(model);
                this.fillTable();
                clear();
                MsgBox.alert(this, "Cập nhật thành công");
            } catch (Exception e) {
            }

        }
    }

    void delete() {
        ChuyenDe cd = dao.selectById(String.valueOf(tblChuyenDe.getValueAt(index, 0)));
        ChuyenDe exist = dao.checkForDelete(cd.getMaCD());
        if (exist.getMaCD().equals(cd.getMaCD())) {
            if (MsgBox.confirm(this, "Đã có khóa học tồn tại trong chuyên đề này, bạn có chắc muốn xóa chuyên đề và các khóa học không?")) {
                String maCD = txtMaChuyenDe.getText();
                dao.delete(maCD);
                this.fillTable();
            }
        } else {
            if (MsgBox.confirm(this, "Bạn có chắc muốn xóa chuyên đề này không?")) {
                try {
                    String maCD = txtMaChuyenDe.getText();
                    dao.delete(maCD);
                    this.fillTable();
                    MsgBox.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                }

            }
        }

    }

    void updateStatus() {
        boolean edit = (index >= 0);
        boolean first = this.index == 0;
        boolean last = this.index == tblChuyenDe.getRowCount() - 1;
        txtMaChuyenDe.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnCapNhat.setEnabled(edit);
        btnXoa.setEnabled(edit);

        btnFirst.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }

    public void first() {
        index = 0;
        tblChuyenDe.setRowSelectionInterval(index, index);
        edit();
    }

    public void prev() {
        if (index > 0) {
            index--;
            tblChuyenDe.setRowSelectionInterval(index, index);
            edit();
        }
    }

    public void next() {
        if (index < tblChuyenDe.getRowCount() - 1) {
            index++;
            tblChuyenDe.setRowSelectionInterval(index, index);
            edit();
        }
    }

    public void last() {
        index = tblChuyenDe.getRowCount() - 1;
        tblChuyenDe.setRowSelectionInterval(index, index);
        edit();
    }

    void clear() {
        txtMaChuyenDe.setText("");
        txtTenChuyenDe.setText("");
        txtThoiLuong.setText("");
        txtThoiLuong.setText("");
        txtHocPhi.setText("");
        txtMoTa.setText("");
        lblLogoChuyenDe.setIcon(null);
        index = -1;
        updateStatus();
    }

    public boolean check() {
        if (txtMaChuyenDe.getText().equals("") || txtTenChuyenDe.getText().equals("") || txtThoiLuong.getText().equals("")
                || txtHocPhi.getText().equals("") || txtMoTa.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập đủ dữ liệu sau đó ấn Thêm", "Error", 1);
            return false;
        } else if (!(txtMaChuyenDe.getText()).matches("CD[0-9]{1,9}")) {
            JOptionPane.showMessageDialog(this, "Sai định dạng mã \n VD : CD07", "Error", 1);
            txtMaChuyenDe.requestFocus();
            return false;
        } else if (!(txtThoiLuong.getText()).matches("[0-9]{1,99}")) {
            JOptionPane.showMessageDialog(this, "Thời lượng phải nhập số dương", "Error", 1);
            txtThoiLuong.requestFocus();
            return false;
        } else if (!(txtThoiLuong.getText()).matches("[0-9]{1,99}")) {
            JOptionPane.showMessageDialog(this, "Học phí phải nhập số dương", "Error", 1);
            txtThoiLuong.requestFocus();
            return false;
        }
        List<ChuyenDe> list = dao.selectAll();
        for (int i = 0; i < list.size(); i++) {
            if (isUpdate) {
            } else {
                if (txtMaChuyenDe.getText().equalsIgnoreCase(list.get(i).getMaCD())) {
                    JOptionPane.showMessageDialog(this, "Trùng Mã Chuyên Đề", "Error", 1);
                    return false;
                }
            }
        }

        return true;
    }

//    public void updateChuyenDe_KhoaHoc() {
//        PanelQuanLyKhoaHoc kh = new PanelQuanLyKhoaHoc();
//        JComboBox<String> cboChuyenDe = new JComboBox();
//        DefaultTableModel model =  (DefaultTableModel)cboChuyenDe.getModel();
//        model.
//        kh.setCboLocChuyenDe(cboChuyenDe);
//    }
}
