/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.NhanVienDAO;
import com.edusys.dao.UserDAO;
import com.edusys.entity.NhanVien;
import com.edusys.entity.User;
import com.edusys.helper.Auth;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author haotn
 */
public class Chao extends javax.swing.JFrame {

    /**
     * Creates new form Progress
     */
    static String taiKhoan = null;
    static String matKhau = null;
    static NhanVien user = null;

    public Chao() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        Run();

    }
    Timer timer;

    public void Run() {
        timer = new Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int curentTime = prgLoad.getValue();
                curentTime += 5;
                prgLoad.setValue(curentTime);
                prgLoad.setStringPainted(true);
                prgLoad.setForeground(Color.blue);
                if (curentTime == 100) {
                    timer.stop();
                    dispose();
                    //  JOptionPane.showMessageDialog(rootPane, "Successfully!");
                    kiemTraTaiKhoan();
                  
                }
            }
        });
        timer.start();
    }
    static public void kiemTraTaiKhoan() {
        UserDAO urDao = new UserDAO();
        List<User> list = urDao.selectAll();

        if (list.size() > 0) {
            User user = urDao.selectAll().get(0);
            taiKhoan = user.getTaiKhoan();
            matKhau = user.getMatKhau();
            NhanVienDAO nvDAO = new NhanVienDAO();
            Chao.user = nvDAO.selectById(taiKhoan);
            Auth.user = Chao.user;
            new MainGUI().setVisible(true);
        }else{
          new DangNhap().setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prgLoad = new javax.swing.JProgressBar();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOAD");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prgLoad.setMinimum(20);
        prgLoad.setToolTipText("");
        prgLoad.setFocusTraversalPolicyProvider(true);
        prgLoad.setInheritsPopupMenu(true);
        prgLoad.setOpaque(true);
        prgLoad.setStringPainted(true);
        getContentPane().add(prgLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 414, 780, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/backgroundProgress.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
                    UIManager.put("RootPane.setupButtonVisible", false);
                } catch (Exception e) {
                    //TODO exception
                }
                new Chao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JProgressBar prgLoad;
    // End of variables declaration//GEN-END:variables
}
