/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.NguoiHocDAO;
import com.edusys.entity.NguoiHoc;
import com.edusys.helper.Auth;
import com.edusys.helper.MsgBox;
import com.edusys.helper.XDate;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.jdatepicker.JDatePicker;
import org.jdatepicker.UtilDateModel;

/**
 *
 * @author haotn
 */
public class PanelQuanLyNguoiHoc extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyNguoiHoc
     */
    public PanelQuanLyNguoiHoc() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brgGioiTinh = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        pnlFormNguoiHoc = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtHoTenNguoiHoc = new javax.swing.JTextField();
        txtMaNguoiHoc = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rdoNu = new javax.swing.JRadioButton();
        rdoNam = new javax.swing.JRadioButton();
        txtNgaySinh = new javax.swing.JTextField();
        txtSoDienThoaii = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtGhiChu_NguoiHoc = new javax.swing.JTextArea();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtNgayDangKy = new javax.swing.JTextField();
        pnlCongCuBangNguoiHoc = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        txtTimKiemNH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiHoc = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Người học");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        pnlFormNguoiHoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormNguoiHoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Email");
        pnlFormNguoiHoc.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Mã người học");
        pnlFormNguoiHoc.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Ghi chú");
        pnlFormNguoiHoc.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Người thêm");
        pnlFormNguoiHoc.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Ngày sinh");
        pnlFormNguoiHoc.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Số điện thoại");
        pnlFormNguoiHoc.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Họ và tên người học");
        pnlFormNguoiHoc.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        txtHoTenNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtHoTenNguoiHoc.setForeground(new java.awt.Color(51, 51, 51));
        txtHoTenNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenNguoiHocActionPerformed(evt);
            }
        });
        pnlFormNguoiHoc.add(txtHoTenNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 260, -1));

        txtMaNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtMaNguoiHoc.setForeground(new java.awt.Color(51, 51, 51));
        pnlFormNguoiHoc.add(txtMaNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, -1));

        txtEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        pnlFormNguoiHoc.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 260, -1));

        rdoNu.setBackground(new java.awt.Color(255, 255, 255));
        brgGioiTinh.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(102, 102, 102));
        rdoNu.setText("Nữ");
        pnlFormNguoiHoc.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        rdoNam.setBackground(new java.awt.Color(255, 255, 255));
        brgGioiTinh.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(102, 102, 102));
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        pnlFormNguoiHoc.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        txtNgaySinh.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtNgaySinh.setForeground(new java.awt.Color(51, 51, 51));
        pnlFormNguoiHoc.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 260, -1));

        txtSoDienThoaii.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtSoDienThoaii.setForeground(new java.awt.Color(51, 51, 51));
        pnlFormNguoiHoc.add(txtSoDienThoaii, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 260, -1));

        txtGhiChu_NguoiHoc.setColumns(20);
        txtGhiChu_NguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtGhiChu_NguoiHoc.setForeground(new java.awt.Color(51, 51, 51));
        txtGhiChu_NguoiHoc.setRows(5);
        jScrollPane5.setViewportView(txtGhiChu_NguoiHoc);

        pnlFormNguoiHoc.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 171, 810, 110));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(102, 102, 102));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Update.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlFormNguoiHoc.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(102, 102, 102));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlFormNguoiHoc.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(102, 102, 102));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Edit.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        pnlFormNguoiHoc.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(102, 102, 102));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlFormNguoiHoc.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Giới tính");
        pnlFormNguoiHoc.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        txtManv.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtManv.setForeground(new java.awt.Color(51, 51, 51));
        pnlFormNguoiHoc.add(txtManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 260, -1));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Ngày đăng ký");
        pnlFormNguoiHoc.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        txtNgayDangKy.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtNgayDangKy.setForeground(new java.awt.Color(51, 51, 51));
        pnlFormNguoiHoc.add(txtNgayDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 260, -1));

        add(pnlFormNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1200, 350));

        pnlCongCuBangNguoiHoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlCongCuBangNguoiHoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLast.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLast.setForeground(new java.awt.Color(102, 102, 102));
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlCongCuBangNguoiHoc.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        btnFirst.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(102, 102, 102));
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlCongCuBangNguoiHoc.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        btnPrev.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(102, 102, 102));
        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlCongCuBangNguoiHoc.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        btnNext.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(102, 102, 102));
        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlCongCuBangNguoiHoc.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        add(pnlCongCuBangNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1200, 50));

        txtTimKiemNH.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTimKiemNH.setForeground(new java.awt.Color(153, 153, 153));
        txtTimKiemNH.setText("Tìm kiếm người học");
        txtTimKiemNH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemNHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemNHFocusLost(evt);
            }
        });
        txtTimKiemNH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemNHKeyReleased(evt);
            }
        });
        add(txtTimKiemNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 250, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblNguoiHoc.setAutoCreateRowSorter(true);
        tblNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNguoiHoc.setGridColor(new java.awt.Color(255, 255, 255));
        tblNguoiHoc.setRowHeight(30);
        tblNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblNguoiHocMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguoiHoc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        isUpdate = false;
        if (checkForm()) {
            insert();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        isUpdate = true;
        if (checkForm()) {
            Update();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void txtHoTenNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenNguoiHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenNguoiHocActionPerformed

    private void txtTimKiemNHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemNHKeyReleased
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_txtTimKiemNHKeyReleased

    private void txtTimKiemNHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemNHFocusGained
        // TODO add your handling code here:
        focusGained();
    }//GEN-LAST:event_txtTimKiemNHFocusGained

    private void txtTimKiemNHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemNHFocusLost
        // TODO add your handling code here:
        focusLost();
    }//GEN-LAST:event_txtTimKiemNHFocusLost

    private void tblNguoiHocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiHocMousePressed
        // TODO add your handling code here:
        row = tblNguoiHoc.getSelectedRow();
        edit();
    }//GEN-LAST:event_tblNguoiHocMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup brgGioiTinh;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pnlCongCuBangNguoiHoc;
    private javax.swing.JPanel pnlFormNguoiHoc;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblNguoiHoc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtGhiChu_NguoiHoc;
    private javax.swing.JTextField txtHoTenNguoiHoc;
    private javax.swing.JTextField txtMaNguoiHoc;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtNgayDangKy;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoDienThoaii;
    private javax.swing.JTextField txtTimKiemNH;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel model;
    UtilDateModel datePickerModel;
    JDatePicker datePicker;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    boolean isUpdate = false;
    NguoiHocDAO dao = new NguoiHocDAO();
    int row;

    public void generateDatePicker() {
        datePickerModel = new UtilDateModel();
        datePicker = new JDatePicker(datePickerModel);
        txtNgaySinh.setLayout(new BorderLayout());
        txtNgaySinh.add(datePicker, BorderLayout.CENTER);
        datePicker.setCursor(Cursor.getDefaultCursor());
//        String date = sdf.format(new Date());
//        int year = Integer.parseInt(date.substring(0, 4));
//        int month = Integer.parseInt(date.substring(5, 7));
//        int day = Integer.parseInt(date.substring(8, 10));
//        datePickerModel.setDate(year, month, day);
        datePickerModel.setValue(new java.util.Date());
    }

    public void setModelTable() {
        model = new DefaultTableModel(new Object[][]{}, new Object[]{"Mã NH", "Họ và tên", "Giới tính", "Ngày sinh", "Điện thoại", "Email", "Ghi chú"});
        tblNguoiHoc.setModel(model);
        JTableHeader header = tblNguoiHoc.getTableHeader();
        header.setFont(new Font("SansSerif", 1, 18));
        header.setForeground(new Color(102, 102, 102));
    }

    public static final Pattern VALID_EMAIL_ADDRESS_REGEX
            = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);

    public static boolean validate(String emailStr) {
        Matcher matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(emailStr);
        return matcher.find();
    }

    public void init() {
        setModelTable();
        fillTable();
        row = -1;
        updateStatus();
        generateDatePicker();
        txtNgayDangKy.setEditable(false);
        txtManv.setEditable(false);
    }

    public void focusGained() {
        if (txtTimKiemNH.getText().equals("Tìm kiếm người học")) {
            txtTimKiemNH.setText("");
        }
        txtTimKiemNH.setForeground(Color.black);
    }

    public void focusLost() {
        if (txtTimKiemNH.getText().equals("")) {
            txtTimKiemNH.setText("Tìm kiếm người học");
            txtTimKiemNH.setForeground(new Color(102, 102, 102));
        }

    }

    public void insert() {
        NguoiHoc nh = getForm();
        try {
            dao.insert(nh);
            fillTable();
            clearForm();
            JOptionPane.showMessageDialog(this, "thêm thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "thêm thất bại ");
        }
    }

    public void Update() {
        NguoiHoc nh = getForm();
        if (MsgBox.confirm(this, "Bạn có chắc muốn cập nhật không?")) {
            try {
                dao.update(nh);
                fillTable();
                clearForm();
                //JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại ");
            }
        }

    }

    public void delete() {
        NguoiHoc nh = getForm();
        if (!Auth.isManager()) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền xóa học viên ");
        } else {

            int chon = JOptionPane.showConfirmDialog(this, "Are you sure delete ? ", "DELETE ", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                try {
                    dao.delete(nh.getMaNH());
                    fillTable();
                    clearForm();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công ");
                }
            }
        }
    }

    public void first() {
        row = 0;
        tblNguoiHoc.setRowSelectionInterval(row, row);
        edit();
    }

    public void next() {
        if (row < tblNguoiHoc.getRowCount() - 1) {
            row++;
            tblNguoiHoc.setRowSelectionInterval(row, row);
            edit();
        }
    }

    public void prev() {
        if (row > 0) {
            row--;
            tblNguoiHoc.setRowSelectionInterval(row, row);
            edit();
        }
    }

    public void last() {
        row = tblNguoiHoc.getRowCount() - 1;
        tblNguoiHoc.setRowSelectionInterval(row, row);
        edit();
    }

    public void updateStatus() {
        boolean edit = (row >= 0);
        boolean first = (row == 0);
        boolean last = (row == tblNguoiHoc.getRowCount() - 1);
        //trạng thái form
        txtMaNguoiHoc.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnCapNhat.setEnabled(edit);
        btnXoa.setEnabled(edit);
        //trang thai dieu hương
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);

        txtManv.setText(Auth.user.getMaNV());
        String date = sdf.format(new Date());
        txtNgayDangKy.setText(date);
    }

    public NguoiHoc setForm(NguoiHoc nh) {
        txtMaNguoiHoc.setText(nh.getMaNH());
        txtHoTenNguoiHoc.setText(nh.getHoTen());
        //txtNgaySinh.setText(String.valueOf(nh.getNgaySinh()));
        datePickerModel.setValue(nh.getNgaySinh());
        txtNgayDangKy.setText(String.valueOf(nh.getNgayDK()));
        txtSoDienThoaii.setText(nh.getDienThoai());
        txtManv.setText(nh.getMaNV());
        txtEmail.setText(nh.getEmail());
        txtGhiChu_NguoiHoc.setText(nh.getGhiChu());
        if (nh.getGioiTinh() == true) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        return nh;
    }

    public NguoiHoc getForm() {
        NguoiHoc nh = new NguoiHoc();
        nh.setMaNH(txtMaNguoiHoc.getText());
        nh.setHoTen(txtHoTenNguoiHoc.getText());
        String date = sdf.format(datePickerModel.getValue());
        nh.setNgaySinh(XDate.toDate(date, "yyyy/MM/dd"));
        nh.setDienThoai(txtSoDienThoaii.getText());
        nh.setMaNV(Auth.user.getMaNV());
        nh.setEmail(txtEmail.getText());
        nh.setGhiChu(txtGhiChu_NguoiHoc.getText());
        if (rdoNam.isSelected()) {
            nh.setGioiTinh(true);
        } else {
            nh.setGioiTinh(false);
        }
        return nh;
    }

    public void clearForm() {
        NguoiHoc nh = new NguoiHoc();
        setForm(nh);
        txtHoTenNguoiHoc.setText("");
        txtNgaySinh.setText("");

        row = -1;
        updateStatus();
    }

    public void edit() {
        String manh = String.valueOf(tblNguoiHoc.getValueAt(row, 0));
        NguoiHoc nh = dao.selectById(manh);
        setForm(nh);
        updateStatus();
    }

    public void fillTable() {
        //DefaultTableModel modelNguoiHoc = (DefaultTableModel) tblNguoiHoc.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtTimKiemNH.getText();
            List<NguoiHoc> list;
            if (keyword.trim().equals("") || keyword.trim().equals("Tìm kiếm người học")) {
                list = dao.selectAll();
            } else {
                list = dao.selectByKeyWord(keyword);
            }
            for (NguoiHoc nh : list) {
                Object[] row = {nh.getMaNH(), nh.getHoTen(), nh.getGioiTinh() ? "Nam" : "Nữ", nh.getNgaySinh(), nh.getDienThoai(), nh.getEmail(), nh.getGhiChu()};
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }

    public void timKiemNguoiHoc() {
        fillTable();
        clearForm();
        row = -1;
        updateStatus();
    }

    public boolean checkForm() {
        if (txtMaNguoiHoc.getText().equals("") || txtHoTenNguoiHoc.getText().equals("") || txtSoDienThoaii.getText().equals("")
                || txtEmail.getText().equals("") || txtNgaySinh.getText().equals("") || txtManv.getText().equals("") || txtGhiChu_NguoiHoc.getText().equals("")
                || (rdoNam.isSelected() == false && rdoNu.isSelected() == false)) {
            JOptionPane.showMessageDialog(this, "Hãy nhập đủ dữ liệu sau đó ấn Thêm", "Error", 1);
            return false;
        } else if (!txtHoTenNguoiHoc.getText().contains(" ")) {
            MsgBox.alert(this, "Vui lòng nhập đầy đủ họ tên!");
            return false;
        } else if (!(txtMaNguoiHoc.getText()).matches("NH[0-9]{1,9}")) {
            JOptionPane.showMessageDialog(this, "Sai định dạng mã \n VD : NH01", "Error", 1);
            txtMaNguoiHoc.requestFocus();
            return false;
        } else if (!(txtSoDienThoaii.getText()).matches("0[3789]{1}[\\d]{8}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng - Vui lòng kiểm tra lại", "Error", 1);
            txtSoDienThoaii.requestFocus();
            return false;
        } // ông xem giúp tui cái mẫu của email nha 
        else if (!validate(txtEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Email không đúng - vui lòng kiểm tra lại ", "Error", 1);
            txtEmail.requestFocus();
            return false;
        }
        List<NguoiHoc> list = dao.selectAll();
        for (int i = 0; i < list.size(); i++) {
            if (isUpdate) {
            } else {
                if (txtMaNguoiHoc.getText().equalsIgnoreCase(list.get(i).getMaNH())) {
                    JOptionPane.showMessageDialog(this, "Trùng Mã Người Học", "Error", 1);
                    return false;
                }
            }
        }

        return true;
    }
}
