/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.KhoaHocDAO;
import com.edusys.dao.ThongKeDAO;
import com.edusys.entity.KhoaHoc;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author haotn
 */
public class PanelBangDiem extends javax.swing.JPanel {

    /**
     * Creates new form PanelBangDiem
     */
    static DefaultTableModel model;
    static JTableHeader header;
    static DefaultComboBoxModel modelCboKhoHoc = new DefaultComboBoxModel();

    public PanelBangDiem() {
        initComponents();
        cboKhoaHoc.setModel(modelCboKhoHoc);
        setModelTable();
        fillComboBoxKhoaHoc();
        fillTableBangDiem();
    }

    public static void refesh() {
        fillComboBoxKhoaHoc();
        fillTableBangDiem();
    }

    public void setModelTable() {
        model = new DefaultTableModel(new Object[][]{}, new Object[]{"Mã người học", "Họ và tên", "Điểm", "Xếp loại"});
        tblBangDiem.setModel(model);
        header = tblBangDiem.getTableHeader();
        header.setForeground(new Color(102, 102, 102));
        header.setFont(new Font("SansSerif", 1, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel37 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        cboKhoaHoc = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Bảng điểm");
        add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jScrollPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblBangDiem.setAutoCreateRowSorter(true);
        tblBangDiem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBangDiem.setGridColor(new java.awt.Color(255, 255, 255));
        tblBangDiem.setRowHeight(30);
        jScrollPane10.setViewportView(tblBangDiem);

        add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 650));

        cboKhoaHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cboKhoaHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaHocActionPerformed(evt);
            }
        });
        add(cboKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 530, 30));

        jLabel48.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(153, 153, 153));
        jLabel48.setText("Khóa học");
        add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void cboKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaHocActionPerformed
        // TODO add your handling code here:
        fillTableBangDiem();
    }//GEN-LAST:event_cboKhoaHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> cboKhoaHoc;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JScrollPane jScrollPane10;
    private static javax.swing.JTable tblBangDiem;
    // End of variables declaration//GEN-END:variables

    static ThongKeDAO tkDAO = new ThongKeDAO();
    static KhoaHocDAO khDAO = new KhoaHocDAO();

    static public void fillComboBoxKhoaHoc() {
        //DefaultComboBoxModel model = (DefaultComboBoxModel) cboKhoaHoc.getModel();
        modelCboKhoHoc.removeAllElements();
        List<KhoaHoc> list = khDAO.selectAll();
        for (KhoaHoc kh : list) {
            modelCboKhoHoc.addElement(kh);
        }
    }

    static public String getXepLoai(double diem) {
        if (diem < 5) {
            return "Chưa đạt";
        }
        if (diem < 6.5) {
            return "Trung bình";
        }
        if (diem < 7.5) {
            return "Khá";
        }
        if (diem < 9) {
            return "Giỏi";
        }
        return "Xuất sắc";
    }

    public static void fillTableBangDiem() {
        //DefaultTableModel model = (DefaultTableModel) tblBangDiem.getModel();
        if (cboKhoaHoc.getSelectedItem() != null) {
            model.setRowCount(0);
            KhoaHoc kh = (KhoaHoc) cboKhoaHoc.getSelectedItem();
            List<Object[]> list = tkDAO.getBangDiem(kh.getMaKH());
            for (Object[] row : list) {
                model.addRow(new Object[]{row[0], row[1], (double) row[2], getXepLoai((double) row[2])});
            }
        }
    }
}
