/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

/**
 *
 * @author haotn
 */
public class PanelGioiThieu extends javax.swing.JPanel {

    /**
     * Creates new form PanelGioiThieu
     */
    public PanelGioiThieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblGioThieu = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Còn nữa!!!");
        jScrollPane14.setViewportView(jTextArea1);

        add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 580, 320));

        lblGioThieu.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblGioThieu.setForeground(new java.awt.Color(153, 153, 153));
        lblGioThieu.setText("Giới thiệu về EduSys");
        add(lblGioThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel46.setText("Mục tiêu chính huấn luyện sinh viên quy trình thực hiện dự án !!!");
        add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel47.setText("EduSys là chương trình dự án mẫu dành cho sinh viên FPT Polytechnic !!!");
        add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblGioThieu;
    // End of variables declaration//GEN-END:variables
}
