/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.KhoaHocDAO;
import com.edusys.dao.ThongKeDAO;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author haotn
 */
public class PanelDiemTheoChuyenDe extends javax.swing.JPanel {

    /**
     * Creates new form PanelDiemTheoChuyenDe
     */
    static DefaultTableModel model;
    static JTableHeader header;

    public PanelDiemTheoChuyenDe() {
        initComponents();
        setModelTable();
        fillTableDiemChuyenDe();
    }

    public void setModelTable() {
        model = new DefaultTableModel(new Object[][]{}, new Object[]{"Chuyên đề", "Số học viên", "Điểm thấp nhất", "Điểm cao nhất", "Điểm trung bình"});
        tblThongKeDiemCD.setModel(model);
        header = tblThongKeDiemCD.getTableHeader();
        header.setForeground(new Color(102, 102, 102));
        header.setFont(new Font("SansSerif", 1, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblThongKeDiemCD = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Thống kê điểm theo chuyên đề");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jScrollPane12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblThongKeDiemCD.setAutoCreateRowSorter(true);
        tblThongKeDiemCD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblThongKeDiemCD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblThongKeDiemCD.setGridColor(new java.awt.Color(255, 255, 255));
        tblThongKeDiemCD.setRowHeight(30);
        jScrollPane12.setViewportView(tblThongKeDiemCD);

        add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel39;
    private javax.swing.JScrollPane jScrollPane12;
    private static javax.swing.JTable tblThongKeDiemCD;
    // End of variables declaration//GEN-END:variables

    ThongKeDAO tkDAO = new ThongKeDAO();
    KhoaHocDAO khDAO = new KhoaHocDAO();

    public void fillTableDiemChuyenDe() {
        DefaultTableModel model = (DefaultTableModel) tblThongKeDiemCD.getModel();
        model.setRowCount(0);
        List<Object[]> list = tkDAO.getDiemChuyenDe();
        for (Object[] row : list) {
            model.addRow(new Object[]{row[0], row[1], row[2], row[3], row[4]});
        }
    }

}
