/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.ThongKeDAO;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author haotn
 */
public class PanelLuongNguoiHoc extends javax.swing.JPanel {

    /**
     * Creates new form PanelLuongNguoihoc
     */
    static DefaultTableModel model;
    static JTableHeader header;

    public PanelLuongNguoiHoc() {
        initComponents();
        setModelTable();
        fillTableLuongNguoiHoc();
    }

    public static void refresh() {
        fillTableLuongNguoiHoc();

    }

    public void setModelTable() {
        model = new DefaultTableModel(new Object[][]{}, new Object[]{"Năm", "Số lượng người học", "Ngày đăng ký sớm nhất", "Ngày đăng ký muộn nhất"});
        tblThongKeNguoiHoc.setModel(model);
        header = tblThongKeNguoiHoc.getTableHeader();
        header.setForeground(new Color(102, 102, 102));
        header.setFont(new Font("SansSerif", 1, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel38 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblThongKeNguoiHoc = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Thống kê lượng người học");
        add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jScrollPane11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblThongKeNguoiHoc.setAutoCreateRowSorter(true);
        tblThongKeNguoiHoc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblThongKeNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblThongKeNguoiHoc.setGridColor(new java.awt.Color(255, 255, 255));
        tblThongKeNguoiHoc.setRowHeight(30);
        jScrollPane11.setViewportView(tblThongKeNguoiHoc);

        add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel38;
    private javax.swing.JScrollPane jScrollPane11;
    private static javax.swing.JTable tblThongKeNguoiHoc;
    // End of variables declaration//GEN-END:variables

    static ThongKeDAO tkDAO = new ThongKeDAO();

    static public void fillTableLuongNguoiHoc() {
        //DefaultTableModel model = (DefaultTableModel) tblThongKeNguoiHoc.getModel();
        model.setRowCount(0);
        List<Object[]> list = tkDAO.getLuongNguoiHoc();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }
}
