/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

/**
 *
 * @author haotn
 */
public class PanelGioiThieu extends javax.swing.JPanel {

    /**
     * Creates new form PanelGioiThieu
     */
    public PanelGioiThieu() {
        initComponents();
        txtGioiThieu.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane14 = new javax.swing.JScrollPane();
        txtGioiThieu = new javax.swing.JTextArea();
        lblGioThieu = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGioiThieu.setColumns(20);
        txtGioiThieu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtGioiThieu.setLineWrap(true);
        txtGioiThieu.setRows(5);
        txtGioiThieu.setText("EduSys - Management là sản phẩm cuối môn của nhóm 5, bao gồm các thành viên: Tiêu Nhựt Hào, Nguyễn Trọng Nhân, Đào Thiên Quốc và Trần Thế Kỷ.\nEduSys - Management trên cơ bản đáp ứng được các yêu cầu về quản lý quy mô nhỏ, với giao diện đơn giản thân thiện với người dùng, mục tiêu thực hiện dự án hướng dẫn cho sinh viên cách tạo ra một phần mềm thực tế, quy trình thực hiện từ khi bắt đầu đến khi hoàn thành dự án.\n");
        txtGioiThieu.setWrapStyleWord(true);
        jScrollPane14.setViewportView(txtGioiThieu);

        add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 580, 320));

        lblGioThieu.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblGioThieu.setForeground(new java.awt.Color(153, 153, 153));
        lblGioThieu.setText("Giới thiệu về EduSys");
        add(lblGioThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel46.setText("Mục tiêu chính huấn luyện sinh viên quy trình thực hiện dự án !!!");
        add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel47.setText("EduSys là chương trình dự án mẫu dành cho sinh viên FPT Polytechnic !!!");
        add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JLabel lblGioThieu;
    private javax.swing.JTextArea txtGioiThieu;
    // End of variables declaration//GEN-END:variables
}
