/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.ChucVuDAO;
import com.edusys.entity.ChucVu;
import com.edusys.helper.Auth;
import com.edusys.helper.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author haotn
 */
public class PanelQuanLyChucVu extends javax.swing.JPanel {

    /**
     * Creates new form PnlQuanLychuVu
     */
    JTableHeader header;
    boolean isUpdate = false;
    String phanQuyen = "";

    public PanelQuanLyChucVu() {
        initComponents();
        setModelTable();
        fillTable();
    }

    public void setModelTable() {
        model = new DefaultTableModel(new Object[][]{}, new Object[]{"Mã chức ", "Chức vụ"});
        tblChucVu.setModel(model);
        header = tblChucVu.getTableHeader();
        header.setFont(new Font("SansSerif", 1, 18));
        header.setForeground(new Color(102, 102, 102));
        tblChucVu.setForeground(new Color(102, 102, 102));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        txtTimChucVu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChucVu = new javax.swing.JTable();
        pnlCongCuBangChucVu = new javax.swing.JPanel();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        pnlFormChucVu = new javax.swing.JPanel();
        txtTenCV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaCV = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnChonPhanQuyen = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Chức vụ");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        txtTimChucVu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTimChucVu.setForeground(new java.awt.Color(153, 153, 153));
        txtTimChucVu.setText("Tìm kiếm chức vụ");
        txtTimChucVu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimChucVuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimChucVuFocusLost(evt);
            }
        });
        txtTimChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimChucVuActionPerformed(evt);
            }
        });
        txtTimChucVu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimChucVuKeyReleased(evt);
            }
        });
        add(txtTimChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 250, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1200, 300));

        tblChucVu.setAutoCreateRowSorter(true);
        tblChucVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblChucVu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChucVu.setGridColor(new java.awt.Color(255, 255, 255));
        tblChucVu.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tblChucVu.setRowHeight(30);
        tblChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChucVu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 300));

        pnlCongCuBangChucVu.setBackground(new java.awt.Color(255, 255, 255));
        pnlCongCuBangChucVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLast.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLast.setForeground(new java.awt.Color(102, 102, 102));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Last.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlCongCuBangChucVu.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        btnFirst.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(102, 102, 102));
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/First.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlCongCuBangChucVu.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        btnPrev.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(102, 102, 102));
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Previous.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlCongCuBangChucVu.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        btnNext.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(102, 102, 102));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Next.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlCongCuBangChucVu.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        add(pnlCongCuBangChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1200, 50));

        pnlFormChucVu.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormChucVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenCV.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormChucVu.add(txtTenCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 250, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Mã chức vụ");
        pnlFormChucVu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Tên chức vụ");
        pnlFormChucVu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        txtMaCV.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pnlFormChucVu.add(txtMaCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 120, -1));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(102, 102, 102));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Update.png"))); // NOI18N
        btnLamMoi.setText("Làm mới ");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        pnlFormChucVu.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(102, 102, 102));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlFormChucVu.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(102, 102, 102));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlFormChucVu.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(102, 102, 102));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/images/Icon_16px/Edit.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        pnlFormChucVu.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        btnChonPhanQuyen.setBackground(new java.awt.Color(255, 255, 255));
        btnChonPhanQuyen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnChonPhanQuyen.setForeground(new java.awt.Color(51, 51, 51));
        btnChonPhanQuyen.setText("Chọn phân quyền");
        pnlFormChucVu.add(btnChonPhanQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        add(pnlFormChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1200, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void tblChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChucVuMouseClicked
        // TODO add your handling code here:
        this.row = tblChucVu.getSelectedRow();
        edit();
    }//GEN-LAST:event_tblChucVuMouseClicked

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        isUpdate = false;
        if (checkForm()) {
            insert();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        isUpdate = true;
        if (checkForm()) {
            update();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtTimChucVuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimChucVuFocusGained
        // TODO add your handling code here:
        focusGained();
    }//GEN-LAST:event_txtTimChucVuFocusGained

    private void txtTimChucVuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimChucVuFocusLost
        // TODO add your handling code here:
        focusLost();
    }//GEN-LAST:event_txtTimChucVuFocusLost

    private void txtTimChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimChucVuActionPerformed

    private void txtTimChucVuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimChucVuKeyReleased
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_txtTimChucVuKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChonPhanQuyen;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCongCuBangChucVu;
    private javax.swing.JPanel pnlFormChucVu;
    private javax.swing.JTable tblChucVu;
    private javax.swing.JTextField txtMaCV;
    private javax.swing.JTextField txtTenCV;
    private javax.swing.JTextField txtTimChucVu;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel model;
    ChucVuDAO dao = new ChucVuDAO();
    int row = -1;

    public void focusGained() {
        if (txtTimChucVu.getText().equals("Tìm kiếm chức vụ")) {
            txtTimChucVu.setText("");
        }
        txtTimChucVu.setForeground(Color.black);
    }

    public void focusLost() {
        if (txtTimChucVu.getText().equals("")) {
            txtTimChucVu.setText("Tìm kiếm chức vụ");
            txtTimChucVu.setForeground(new Color(102, 102, 102));
        }
    }

    public void fillTable() {
        //DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0); // Xóa tất cả các hàng trên JTable
        try {
            List<ChucVu> list;
            if (txtTimChucVu.getText().equals("") || txtTimChucVu.getText().equals("Tìm kiếm chức vụ")) {
                list = dao.selectAll(); // Đọc dữ liệu từ CSDL
            } else {
                list = dao.selectByKeyword(txtTimChucVu.getText());
            }
            ChucVuDAO cvDAO = new ChucVuDAO();
            for (ChucVu nv : list) {
                Object[] row = {nv.getMaCV(), nv.getTenCV()};
                model.addRow(row); // Thêm một hàng vào JTable
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
//JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    public void setForm(ChucVu nv) {
        txtMaCV.setText(nv.getMaCV());
        txtTenCV.setText(nv.getTenCV());
    }

    public static void setPhanQuyen() {
    }

    public ChucVu getForm() {
        ChucVu nv = new ChucVu();
        nv.setMaCV(txtMaCV.getText());
        nv.setTenCV(txtTenCV.getText());
        return nv;
    }

    public static void getPhanQuyen() {
    }

    public void clearForm() {
        ChucVu nv = new ChucVu();
        this.setForm(nv);
        //if(txtHoTenNV.getText().equals("nullnull")){
        //txtHoTenNV.setText("");
        // }
        this.row = -1;
        this.updateStatus();
    }

    public void edit() {
        String macv = (String) tblChucVu.getValueAt(this.row, 0);
        ChucVu nv = dao.selectById(macv);
        this.setForm(nv);
        this.updateStatus();
    }

    public void insert() {
        ChucVu nv = getForm();
        try {
            dao.insert(nv);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "thêm mới thành công!");
        } catch (Exception e) {
            //System.out.println(e);
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    public void update() {
        ChucVu nv = getForm();
        if (MsgBox.confirm(this, "Bạn có chắc muốn cập nhật nhân viên này không?")) {
            try {
                dao.update(nv);
                this.fillTable();
                clearForm();
                //MsgBox.alert(this, "Cập nhật thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại!");
            }
        }

    }

    public boolean checkForm() {
        ChucVu nv = getForm();
        if (isUpdate == false) {
            if (txtMaCV.getText().equals("") || txtTenCV.getText().equals("") || phanQuyen.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập (chọn) đầy đủ thông tin trước khi nhấn nút thêm!", "Error", 1);
                return false;
            }
        }
        for (int i = 0; i < dao.selectAll().size(); i++) {
            if (isUpdate == true) {
            } else {
                if (txtMaCV.getText().equals(dao.selectAll().get(i).getMaCV())) {
                    JOptionPane.showMessageDialog(this, "Mã chức vụ không được phép trùng!", "Error", 1);
                    return false;
                }
            }
        }
        return true;
    }

    public void delete() {
        if (!Auth.isManager()) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền chức vụ viên!", "Error", 1);
        } else {
            if (txtMaCV.getText().equals("adminQT")) {
                JOptionPane.showMessageDialog(this, "Không thể xóa chức vụ admin!", "Error", 1);
            } else if (dao.selectHaveEmployee(txtMaCV.getText()).size() > 0) {
                if (MsgBox.confirm(this, "Đã có nhân viên trong chức vụ này, bạn có chắc chắn muốn xóa chức vụ không?")) {
                    try {
                        dao.delete(txtMaCV.getText());
                        this.fillTable();
                        this.clearForm();
                        //MsgBox.alert(this, "Xóa thành công!");
                    } catch (Exception e) {
                        MsgBox.alert(this, "Xóa thất bại!");
                    }
                }
            } else if (MsgBox.confirm(this, "Bạn thực sự muốn xóa nhân viên này?")) {
                try {
                    dao.delete(txtMaCV.getText());
                    this.fillTable();
                    this.clearForm();
                    //MsgBox.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }

    public void first() {
        this.row = 0;
        tblChucVu.setRowSelectionInterval(row, row);
        this.edit();
    }

    public void prev() {
        if (this.row > 0) {
            this.row--;
            tblChucVu.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    public void next() {
        if (this.row < tblChucVu.getRowCount() - 1) {
            this.row++;
            tblChucVu.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    public void last() {
        this.row = tblChucVu.getRowCount() - 1;
        tblChucVu.setRowSelectionInterval(row, row);
        this.edit();
    }

    public void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblChucVu.getRowCount() - 1);
        // Trạng thái Form
        txtMaCV.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnCapNhat.setEnabled(edit);
        btnXoa.setEnabled(edit);
        // Trạng thái điều hướng
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);

    }
}
