/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.dao.KhoaHocDAO;
import com.edusys.dao.ThongKeDAO;
import com.edusys.entity.ChuyenDe;
import com.edusys.entity.KhoaHoc;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author haotn
 */
public class PanelDoanhThu extends javax.swing.JPanel {

    /**
     * Creates new form PanelDoanhThu
     */
    static DefaultTableModel model;
    static JTableHeader header;
    static DefaultComboBoxModel modelCboNam = new DefaultComboBoxModel<>();

    public PanelDoanhThu() {
        initComponents();
        cboNam.setModel(modelCboNam);
        setModelTable();
        fillComboBoxNam();
        fillTableDoanhThu();
    }

    public static void refresh() {
        fillComboBoxNam();
        fillTableDoanhThu();
    }

    public void setModelTable() {

        model = new DefaultTableModel(new Object[][]{}, new Object[]{"Chuyên đề", "Số khóa học", "Doanh thu", "Học phí thấp nhất", "Học phí cao nhất", "Học phí trung bình"});
        tblDoanhThu.setModel(model);
        header = tblDoanhThu.getTableHeader();
        header.setForeground(new Color(102, 102, 102));
        header.setFont(new Font("SansSerif", 1, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDoanhThu = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoanhThu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("Doanh thu");
        pnlDoanhThu.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        jScrollPane13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblDoanhThu.setAutoCreateRowSorter(true);
        tblDoanhThu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDoanhThu.setGridColor(new java.awt.Color(255, 255, 255));
        tblDoanhThu.setRowHeight(30);
        jScrollPane13.setViewportView(tblDoanhThu);

        pnlDoanhThu.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 650));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(153, 153, 153));
        jLabel43.setText("Năm");
        pnlDoanhThu.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 50, 30));

        cboNam.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cboNam.setForeground(new java.awt.Color(51, 51, 51));
        cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamActionPerformed(evt);
            }
        });
        pnlDoanhThu.add(cboNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 62, 420, 30));

        add(pnlDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cboNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamActionPerformed
        // TODO add your handling code here:
        fillTableDoanhThu();
    }//GEN-LAST:event_cboNamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> cboNam;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JPanel pnlDoanhThu;
    private static javax.swing.JTable tblDoanhThu;
    // End of variables declaration//GEN-END:variables

    static ThongKeDAO tkDAO = new ThongKeDAO();
    static KhoaHocDAO khDAO = new KhoaHocDAO();

    static public void fillComboBoxNam() {
        //DefaultComboBoxModel model = (DefaultComboBoxModel) cboNam.getModel();
        modelCboNam.removeAllElements();
        List<Integer> list = khDAO.selectYears();
        for (Integer year : list) {
            modelCboNam.addElement(year);
        }
    }

    static public void fillTableDoanhThu() {
        // DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();
        int nam = -1;
        try {
            nam = (Integer) cboNam.getSelectedItem();
        } catch (Exception e) {
        }

        if (nam != -1) {
            model.setRowCount(0);

            List<Object[]> list = tkDAO.getDoanhThu(nam);
            for (Object[] row : list) {
                model.addRow(row);
            }
        }
    }
}
